CREATE TABLE [DTG].[Term] (
    [TermId]                        INT            IDENTITY (1, 1) NOT NULL,
    [TermCode]                      VARCHAR (30)   NOT NULL,
    [Name]                          VARCHAR (200)  NOT NULL,
    [NameEN]                        VARCHAR (200)  NULL,
    [Description]                   VARCHAR (2000) NOT NULL,
    [DescriptionEN]                 VARCHAR (2000) NULL,
    [ModuleId]                      INT            NULL,
    [Type]                          TINYINT        NOT NULL,
    [DataOwner]                     INT            NULL,
    [DataManager]                   INT            NULL,
    [DataSteward]                   INT            NULL,
    [BaseTermId]                    INT            NULL,
    [Sensitivity]                   TINYINT        CONSTRAINT [DF_Term_Sensitivity] DEFAULT ((0)) NULL,
    [UserName]                      VARCHAR (10)   NULL,
    [HostName]                      VARCHAR (20)   NULL,
    [SystemDate]                    DATETIME       NULL,
    [UpdateUserName]                VARCHAR (10)   NULL,
    [UpdateHostName]                VARCHAR (20)   NULL,
    [UpdateSystemDate]              DATETIME       NULL,
    [HostIP]                        VARCHAR (15)   NULL,
    [CopyWriterApproval]            TINYINT        CONSTRAINT [DF_Term_CopyWriterApprovement] DEFAULT ((0)) NULL,
    [UseCount]                      INT            NULL,
    [TermType]                      TINYINT        NULL,
    [HashTag]                       VARCHAR (50)   NULL,
    [IsPrivateData]                 TINYINT        NULL,
    [IsBusinessUnitTerm]            TINYINT        NULL,
    [ValidatedByBusinessUnit]       TINYINT        NULL,
    [ValidatedByCustomerRightsUnit] TINYINT        NULL,
    [Level1Domain]                  INT            NULL,
    [Level2Domain]                  INT            NULL,
    [Accessibility]                 TINYINT        DEFAULT ((1)) NULL,
    [Integrity]                     TINYINT        DEFAULT ((1)) NULL,
    CONSTRAINT [PK_Term] PRIMARY KEY CLUSTERED ([TermId] ASC) WITH (FILLFACTOR = 95)
);

