
/* KUWAIT TURKISH PARTICIPATION BANK INC.
*
*  All rights are reserved. Reproduction or transmission in whole or in part, in
*  any form or by any means, electronic, mechanical or otherwise, is prohibited
*  without the prior written consent of the copyright owner.
*
*
*  Generator Information
*		Generator				: BOAContainer
*		Generated By			: karadayi
*		Generated Date			: 05/01/2018
*		File Version			: 1.0
*		Purpose					: <Lütfen açıklama giriniz.>
*		Last Modified By		: karadayi
*		Last Modification Date	: 05/01/2018
*
*/
CREATE PROCEDURE [DTG].[del_TableColumnSubsetCriteria]
(
	@DBName VARCHAR(20),
	@SchemaName VARCHAR(20),
	@TableName VARCHAR(50),
	@ColumnName VARCHAR(100)
)
AS
SET NOCOUNT ON
BEGIN
	DECLARE @DataMaskTypeId TINYINT = NULL

	SELECT @DataMaskTypeId = DataMaskTypeId
	  FROM DTG.TableColumnDataMask WITH (NOLOCK)
	 WHERE DBName = @DBName
		AND SchemaName = @SchemaName
		AND TableName = @TableName
		AND ColumnName = @ColumnName

	IF @DataMaskTypeId IS NULL
	BEGIN
		DELETE FROM DTG.TableColumnDataMask
		 WHERE DBName = @DBName
		   AND SchemaName = @SchemaName
		   AND TableName = @TableName
		   AND ColumnName = @ColumnName
	END
	ELSE
	BEGIN
		UPDATE DTG.TableColumnDataMask
		   SET SubsetCriteria = NULL
			  ,SubsetOperator = NULL
		 WHERE DBName = @DBName
		   AND SchemaName = @SchemaName
		   AND TableName = @TableName
		   AND ColumnName = @ColumnName
	END
END