
/* KUWAIT TURKISH PARTICIPATION BANK INC.
*
*  All rights are reserved. Reproduction or transmission in whole or in part, in
*  any form or by any means, electronic, mechanical or otherwise, is prohibited
*  without the prior written consent of the copyright owner.
*
*
*  Generator Information
*		Generator				: BOAContainer
*		Generated By			: karadayi
*		Generated Date			: 09/05/2016
*		File Version			: 1.0
*		Purpose					: <Lütfen açıklama giriniz.>
*		Last Modified By		: karadayi
*		Last Modification Date	: 09/05/2017
*
*/
CREATE PROCEDURE [DTG].[del_TableDataMaskException]
(
	@DBName VARCHAR(50),
	@SchemaName VARCHAR(20),
	@TableName VARCHAR(50)
)
AS
	SET NOCOUNT ON

	DELETE FROM DTG.TableDataMaskException
	 WHERE DBName = @DBName 
	   AND SchemaName = @SchemaName 
	   AND TableName = @TableName