/* KUWAIT TURKISH PARTICIPATION BANK INC.
*
*  All rights are reserved. Reproduction or transmission in whole or in part in
*  any form or by any means electronic mechanical or otherwise is prohibited
*  without the prior written consent of the copyright owner.
*
*
*  Generator Information
*		Generator				: BOAContainer
*		Generated By			: karadayi
*		Generated Date			: 27/12/2017
*		File Version			: 1.0
*		Purpose					: Data Governance - Veri Modelleme Sistemi Parametreleri için insert prosedürü
*		Last Modified By		: karadayi
*		Last Modification Date	: 
*
*/
CREATE PROCEDURE [DTG].[ins_Parameter]
(
	@ParamType VARCHAR(20)
    ,@ParamCode VARCHAR(20)
    ,@ParamValue VARCHAR(50)
    ,@ParamDescription VARCHAR(200) = NULL
    ,@ParamValue2 VARCHAR(50) = NULL
    ,@ParamValue3 VARCHAR(50) = NULL
    ,@ParamValue4 VARCHAR(50) = NULL
    ,@ParamValue5 VARCHAR(50) = NULL
    ,@LanguageId INT
    ,@SortOrder TINYINT = NULL
)
AS
	SET NOCOUNT ON
BEGIN

	INSERT INTO [DTG].[Parameter]
           ([ParamType]
           ,[ParamCode]
           ,[ParamValue]
           ,[ParamDescription]
           ,[ParamValue2]
           ,[ParamValue3]
           ,[ParamValue4]
           ,[ParamValue5]
           ,[LanguageId]
           ,[SortOrder])
     VALUES
           (@ParamType
           ,@ParamCode
           ,@ParamValue
           ,@ParamDescription
           ,@ParamValue2
           ,@ParamValue3
           ,@ParamValue4
           ,@ParamValue5
           ,@LanguageId
           ,@SortOrder)
END