
/* KUWAIT TURKISH PARTICIPATION BANK INC.
*
*  All rights are reserved. Reproduction or transmission in whole or in part, in
*  any form or by any means, electronic, mechanical or otherwise, is prohibited
*  without the prior written consent of the copyright owner.
*
*
*  Generator Information
*		Generator				: BOAContainer
*		Generated By			: karadayi
*		Generated Date			: 03/03/2016 10:17:29
*		File Version			: 1.0
*		Purpose					: <Lütfen açıklama giriniz.>
*		Last Modified By		: karadayi
*		Last Modification Date	: 03/03/2016 10:17:29
*
*/
CREATE PROCEDURE [DTG].[ins_TermRule]
(
	@TermId INT = NULL,
	@TemplateType TINYINT = NULL,
	@Value VARCHAR(200) = NULL,
	@AlertStatus TINYINT = NULL
)
AS
	SET NOCOUNT ON;
BEGIN

	INSERT INTO [DTG].[TermRule]
	(
		TermId,
		TemplateType,
		Value,
		AlertStatus
	)
	VALUES
	(
		@TermId,
		@TemplateType,
		@Value,
		@AlertStatus
	)

	SELECT CAST(SCOPE_IDENTITY() AS INT)

END