
/* KUWAIT TURKISH PARTICIPATION BANK INC.
*
*  All rights are reserved. Reproduction or transmission in whole or in part, in
*  any form or by any means, electronic, mechanical or otherwise, is prohibited
*  without the prior written consent of the copyright owner.
*
*
*  Generator Information
*		Generator				: BOAContainer
*		Generated By			: karadayi
*		Generated Date			: 13/03/2016 14:07:23
*		File Version			: 1.0
*		Purpose					: <Lütfen açıklama giriniz.>
*		Last Modified By		: karadayi
*		Last Modification Date	: 13/03/2016 14:07:23
*
*/
CREATE PROCEDURE [DTG].[ins_Attribute]
(
	@EntityId INT = NULL,
	@TermId INT = NULL,
	@AttributeType TINYINT,
	@DataType VARCHAR(50),
	@Nullable TINYINT = NULL,
	@IsKey TINYINT = NULL,
	@IsCollection TINYINT = NULL,
	@ReferenceAttributeId INT = NULL,
	@Sensitivity TINYINT = NULL,
	@UserName VARCHAR(10) = NULL,
	@HostName VARCHAR(20) = NULL,
	@HostIP VARCHAR(15) = NULL
)
AS
	SET NOCOUNT ON;
BEGIN

	INSERT INTO [DTG].[Attribute]
	(
		EntityId,
		TermId,
		AttributeType,
		DataType,
		Nullable,
		IsKey,
		IsCollection,
		ReferenceAttributeId,
		Sensitivity,
		UserName,
		HostName,
		SystemDate,
		HostIP
	)
	VALUES
	(
		@EntityId,
		@TermId,
		@AttributeType,
		@DataType,
		@Nullable,
		@IsKey,
		@IsCollection,
		@ReferenceAttributeId,
		@Sensitivity,
		@UserName,
		@HostName,
		GETDATE(),
		@HostIP
	)

	SELECT CAST(SCOPE_IDENTITY() AS INT)

END