
/* KUWAIT TURKISH PARTICIPATION BANK INC.
*
*  All rights are reserved. Reproduction or transmission in whole or in part, in
*  any form or by any means, electronic, mechanical or otherwise, is prohibited
*  without the prior written consent of the copyright owner.
*
*
*  Generator Information
*		Generator				: BOAContainer
*		Generated By			: karadayi
*		Generated Date			: 11/03/2016 08:18:08
*		File Version			: 1.0
*		Purpose					: <Lütfen açıklama giriniz.>
*		Last Modified By		: karadayi
*		Last Modification Date	: 17/05/2016 08:18:08
*
*/
CREATE PROCEDURE [DTG].[ins_TableColumn]
(
	@TableId INT,
	@TermId INT = NULL,
	@ColumnName VARCHAR(100),
	@IsKey TINYINT,
	@DataTypeChanged TINYINT = NULL,
	@DataType VARCHAR(50),
	@Nullable TINYINT = NULL,
	@Sensitivity TINYINT = NULL,
	@Description VARCHAR(500) = NULL,
	@IsReference TINYINT = 0,
	@IsIdentity TINYINT = 0
)
AS
	SET NOCOUNT ON;
BEGIN

	DECLARE @InsertedId INT

	INSERT INTO [DTG].[TableColumn]
	(
		TableId,
		TermId,
		ColumnName,
		IsKey,
		DataTypeChanged,
		DataType,
		Nullable,
		Sensitivity,
		[Description],
		IsReference,
		IsIdentity
	)
	VALUES
	(
		@TableId,
		@TermId,
		@ColumnName,
		@IsKey,
		@DataTypeChanged,
		@DataType,
		@Nullable,
		@Sensitivity,
		@Description,
		@IsReference,
		@IsIdentity
	)

	SELECT @InsertedId = CAST(SCOPE_IDENTITY() AS INT)

	IF @TermId IS NOT NULL
	BEGIN
		IF NOT EXISTS(SELECT ColumnRuleId 
						FROM DTG.ColumnRule WITH (NOLOCK) 
					   WHERE TermId = @TermId)
		BEGIN
			INSERT INTO DTG.ColumnRule(TermId, DataType, ColumnName)
			VALUES(@TermId, @DataType, @ColumnName)
		END
	END

	SELECT @InsertedId
END