
/* KUWAIT TURKISH PARTICIPATION BANK INC.
*
*  All rights are reserved. Reproduction or transmission in whole or in part, in
*  any form or by any means, electronic, mechanical or otherwise, is prohibited
*  without the prior written consent of the copyright owner.
*
*
*  Generator Information
*		Generator				: BOAContainer
*		Generated By			: karadayi
*		Generated Date			: 21/03/2018
*		File Version			: 1.0
*		Purpose					: KVKK Kapsamında Veri Silme Taleplerini Karşılayabilmek Adını Müşteri Verilerinin Ne Olduğunu Bulan Sistemin Yönetim Detay Tablosunu Doldurur
*		Last Modified By		: karadayi
*		Last Modification Date	: 21/03/2018
*
*/
CREATE PROCEDURE [DTG].[ins_CustomerDataRequestDetail]
(
	@CustomerDataRequestId INT,
	@TermId INT,
	@SearchValue NVARCHAR(50),
	@UserName VARCHAR(10) = NULL,
	@HostName VARCHAR(20) = NULL,
	@HostIP VARCHAR(15) = NULL
)
AS
SET NOCOUNT ON
BEGIN

	IF NOT EXISTS(SELECT TOP 1 1 FROM [DTG].[CustomerDataRequestDetail] WITH (NOLOCK) WHERE CustomerDataRequestId = @CustomerDataRequestId AND TermId = @TermId)
	BEGIN
		INSERT INTO [DTG].[CustomerDataRequestDetail]
			([CustomerDataRequestId]
			,[TermId]
			,[SearchValue]
			,[UserName]
			,[HostName]
			,[SystemDate]
			,[HostIP])
		VALUES
			(@CustomerDataRequestId
			,@TermId
			,@SearchValue
			,@UserName
			,@HostName
			,GETDATE()
			,@HostIP)
	END
	ELSE
	BEGIN
		EXEC [DTG].[upd_CustomerDataRequestDetail] @CustomerDataRequestId, @TermId, @SearchValue, @UserName, @HostName, @HostIP
	END

END