
/* KUWAIT TURKISH PARTICIPATION BANK INC.
*
*  All rights are reserved. Reproduction or transmission in whole or in part, in
*  any form or by any means, electronic, mechanical or otherwise, is prohibited
*  without the prior written consent of the copyright owner.
*
*
*  Generator Information
*		Generator				: BOAContainer
*		Generated By			: karadayi
*		Generated Date			: 10/07/2018
*		File Version			: 1.0
*		Purpose					: <Lütfen açıklama giriniz.>
*		Last Modified By		: karadayi
*		Last Modification Date	: 27/07/2018
*
*/
CREATE PROCEDURE [DTG].[ins_ScriptDefinition]
@ScriptText VARCHAR(5000)
,@ScriptTag VARCHAR(100)
,@ScriptGroup VARCHAR(50)
,@SortOrder TINYINT = NULL
,@UserName VARCHAR(10)
,@HostName VARCHAR(20)
,@HostIP VARCHAR(15)
AS
SET NOCOUNT ON
BEGIN
   INSERT INTO [DTG].[ScriptDefinition]
           ([ScriptText]
           ,[ScriptTag]
           ,[ScriptGroup]
		   ,[SortOrder]
           ,[UserName]
           ,[HostName]
           ,[SystemDate]
           ,[HostIP])
     VALUES
           (@ScriptText
           ,@ScriptTag
           ,@ScriptGroup
		   ,@SortOrder
           ,@UserName
           ,@HostName
           ,GETDATE()
           ,@HostIP)

	SELECT CAST(SCOPE_IDENTITY() AS INT)
END