
/* KUWAIT TURKISH PARTICIPATION BANK INC.
*
*  All rights are reserved. Reproduction or transmission in whole or in part, in
*  any form or by any means, electronic, mechanical or otherwise, is prohibited
*  without the prior written consent of the copyright owner.
*
*
*  Generator Information
*		Generator				: BOAContainer
*		Generated By			: karadayi
*		Generated Date			: 21/03/2018
*		File Version			: 1.0
*		Purpose					: KVKK Kapsamında Veri Silme Taleplerini Karşılayabilmek Adını Müşteri Verilerinin Ne Olduğunu Bulan Sistemin Yönetim Tablosunu Doldurur
*		Last Modified By		: karadayi
*		Last Modification Date	: 21/03/2018
*
*/
CREATE PROCEDURE [DTG].[ins_CustomerDataRequest]
(
	@UniqueKeyForCustomer VARCHAR(50),
	@IsProcessed TINYINT = 0,
	@UserName VARCHAR(10) = NULL,
	@HostName VARCHAR(20) = NULL,
	@HostIP VARCHAR(15) = NULL
)
AS
SET NOCOUNT ON
BEGIN
	DECLARE @CustomerDataRequestId INT

	SELECT @CustomerDataRequestId = CustomerDataRequestId
	  FROM [DTG].[CustomerDataRequest] WITH (NOLOCK)
	 WHERE UniqueKeyForCustomer = @UniqueKeyForCustomer --AND
		   --IsProcessed = @IsProcessed

	IF @CustomerDataRequestId IS NULL
	BEGIN
		INSERT INTO [DTG].[CustomerDataRequest]
			([UniqueKeyForCustomer]
			,[IsProcessed]
			,[UserName]
			,[HostName]
			,[SystemDate]
			,[HostIP])
		VALUES
			(@UniqueKeyForCustomer
			,@IsProcessed
			,@UserName
			,@HostName
			,GETDATE()
			,@HostIP)

		SELECT @CustomerDataRequestId = CAST(SCOPE_IDENTITY() AS INT)
	END

	SELECT @CustomerDataRequestId
END