
/* KUWAIT TURKISH PARTICIPATION BANK INC.
*
*  All rights are reserved. Reproduction or transmission in whole or in part, in
*  any form or by any means, electronic, mechanical or otherwise, is prohibited
*  without the prior written consent of the copyright owner.
*
*
*  Generator Information
*		Generator				: BOAContainer
*		Generated By			: karadayi
*		Generated Date			: 09/03/2016
*		File Version			: 1.0
*		Purpose					: <Lütfen açıklama giriniz.>
*		Last Modified By		: karadayi
*		Last Modification Date	: 09/03/2016
*
*/
CREATE PROCEDURE [DTG].[ins_DataTypeMatch]
(
	@DataTypeId INT,
	@DataTypeLanguageId TINYINT,
	@Value VARCHAR(50)
)
AS
SET NOCOUNT ON;
BEGIN

	IF NOT EXISTS(SELECT 1 FROM [DTG].[DataTypeMatch] WITH (NOLOCK)
				   WHERE [DataTypeId] = @DataTypeId
				     AND [DataTypeLanguageId] = @DataTypeLanguageId)
	BEGIN
		INSERT INTO [DTG].[DataTypeMatch]
			   ([DataTypeId]
			   ,[DataTypeLanguageId]
			   ,[Value])
		 VALUES
			   (@DataTypeId
			   ,@DataTypeLanguageId
			   ,@Value)
	END
	ELSE
	BEGIN
		UPDATE [DTG].[DataTypeMatch]
		   SET [Value] = @Value
		 WHERE [DataTypeId] = @DataTypeId
			   AND [DataTypeLanguageId] = @DataTypeLanguageId
	END

END