
/* KUWAIT TURKISH PARTICIPATION BANK INC.
*
*  All rights are reserved. Reproduction or transmission in whole or in part, in
*  any form or by any means, electronic, mechanical or otherwise, is prohibited
*  without the prior written consent of the copyright owner.
*
*
*  Generator Information
*		Generator				: BOAContainer
*		Generated By			: karadayi
*		Generated Date			: 29/09/2016
*		File Version			: 1.0
*		Purpose					: <Lütfen açıklama giriniz.>
*		Last Modified By		: karadayi
*		Last Modification Date	: 04/10/2017
*
*/
CREATE PROCEDURE [DTG].[sel_ApprovedTable]
	@ServerName VARCHAR(20) = NULL,
	@DBName VARCHAR(20),
	@SchemaName VARCHAR(20)
AS
	SET NOCOUNT ON;

	SELECT DISTINCT
		TBL.TableId,
		TBL.DBName,
		TBL.SchemaName,
		TBL.TableName,
		TBL.TermId,
		TBL.IsEntity,
		TBL.[Description],
		TBL.[Status]
	  FROM DTG.[Table] TBL WITH (NOLOCK)
	 INNER JOIN [DTG].[TableDesignPackage] TDP WITH (NOLOCK)
		ON TDP.DBName = TBL.DBName
		AND TDP.SchemaName = TBL.SchemaName
		AND TDP.TableName = TBL.TableName
		AND TDP.[Status] = 1
	 WHERE TBL.DBName = @DBName AND
		   TBL.SchemaName = @SchemaName AND
		   TBL.[Status] = 1