
/* KUWAIT TURKISH PARTICIPATION BANK INC.
*
*  All rights are reserved. Reproduction or transmission in whole or in part, in
*  any form or by any means, electronic, mechanical or otherwise, is prohibited
*  without the prior written consent of the copyright owner.
*
*
*  Generator Information
*		Generator				: BOAContainer
*		Generated By			: karadayi
*		Generated Date			: 10/07/2018
*		File Version			: 1.0
*		Purpose					: <Lütfen açıklama giriniz.>
*		Last Modified By		: karadayi
*		Last Modification Date	: 27/07/2018
*
*/
CREATE PROCEDURE [DTG].[sel_ScriptInventory]
@ScriptInventoryType TINYINT
,@ScriptDefinitionId INT = NULL
,@TermId INT = NULL
,@DatabaseName VARCHAR(100)
,@SchemaName VARCHAR(100)
,@TableName VARCHAR(100)
,@ColumnName VARCHAR(50)
AS
SET NOCOUNT ON
BEGIN
   SELECT INV.[ScriptInventoryId]
      ,INV.[ScriptInventoryType]
      ,INV.[ScriptDefinitionId]
	  ,LEFT(D.[ScriptText], 
	   /* Tek satır ise 50. karaktere kadar, birden fazla satır içeriyorsa ilk satırın sonuna kadar al. */
		CASE ((CHARINDEX(CHAR(10), D.[ScriptText])) - 1)
			WHEN -1 THEN 50
			ELSE ((CHARINDEX(CHAR(10), D.[ScriptText])) - 1)
		END
		) + ' [...]' AS ScriptText
	  ,D.[ScriptTag]
	  ,D.[ScriptGroup]
	  ,D.[SortOrder]
      ,INV.[TermId]
	  ,T.[Name] AS TermName
      ,INV.[DatabaseName]
      ,INV.[SchemaName]
      ,INV.[TableName]
      ,INV.[ColumnName]
      ,INV.[UserName]
      ,INV.[HostName]
      ,INV.[SystemDate]
      ,INV.[UpdateUserName]
      ,INV.[UpdateHostName]
      ,INV.[UpdateSystemDate]
      ,INV.[HostIP]
	 FROM DTG.ScriptInventory AS INV WITH (NOLOCK)
	INNER JOIN DTG.ScriptDefinition AS D WITH (NOLOCK) ON D.[ScriptDefinitionId] = INV.[ScriptDefinitionId]
	LEFT JOIN DTG.Term AS T WITH (NOLOCK) ON T.[TermId] = INV.[TermId]
	WHERE
		[ScriptInventoryType] = @ScriptInventoryType AND
		(@ScriptDefinitionId IS NULL OR INV.[ScriptDefinitionId] = @ScriptDefinitionId) AND
		(@TermId IS NULL OR INV.[TermId] = @TermId) AND
		(@DatabaseName IS NULL OR INV.[DatabaseName] = @DatabaseName) AND
		(@SchemaName IS NULL OR INV.[SchemaName] = @SchemaName) AND
		(@TableName IS NULL OR INV.[TableName] = @TableName) AND
		(@ColumnName IS NULL OR INV.[ColumnName] = @ColumnName)
END