
/* KUWAIT TURKISH PARTICIPATION BANK INC.
*
*  All rights are reserved. Reproduction or transmission in whole or in part, in
*  any form or by any means, electronic, mechanical or otherwise, is prohibited
*  without the prior written consent of the copyright owner.
*
*
*  Generator Information
*		Generator				: BOAContainer
*		Generated By			: karadayi
*		Generated Date			: 04/03/2016 16:28:21
*		File Version			: 1.0
*		Purpose					: <Lütfen açıklama giriniz.>
*		Last Modified By		: karadayi
*		Last Modification Date	: 04/03/2016 16:28:21
*
*/
CREATE PROCEDURE [DTG].[sel_Sensitivity]
@LanguageId TINYINT = 1
AS
	SET NOCOUNT ON;

	SELECT 
		ParamCode AS [SensitivityId]
       ,ParamValue AS [Name]
	FROM [CORParameter].[dbo].[Parameter] WITH (NOLOCK)
	WHERE
		ParamGroupCode = 'DTG' AND
		ParamType = 'SENSITIVITY' AND
		LanguageId = @LanguageId
	ORDER BY ParamCode