
/* KUWAIT TURKISH PARTICIPATION BANK INC.
*
*  All rights are reserved. Reproduction or transmission in whole or in part, in
*  any form or by any means, electronic, mechanical or otherwise, is prohibited
*  without the prior written consent of the copyright owner.
*
*
*  Generator Information
*		Generator				: BOAContainer
*		Generated By			: karadayi
*		Generated Date			: 10/05/2016
*		File Version			: 1.0
*		Purpose					: <Lütfen açıklama giriniz.>
*		Last Modified By		: karadayi
*		Last Modification Date	: 15/06/2016
*
*/
CREATE PROCEDURE [DTG].[sel_TableKeyColumnByTableTermId]
(
	@TermId INT
)
AS
	SET NOCOUNT ON

	SELECT CLM.TableColumnId,
		CLM.TableId,
		CLM.TermId,
		T.Name AS TermName,
		T.Level1Domain AS TermLevel1Domain,
		T.Level2Domain AS TermLevel2Domain,
		CLM.ColumnName,
		CLM.IsKey,
		CLM.DataTypeChanged,
		CLM.DataType,
		CLM.Nullable,
		CLM.Sensitivity,
		CLM.[Description],
		CLM.IsReference,
		CLM.IsIdentity
	  FROM [DTG].[Table] AS TBL WITH (NOLOCK)
	 INNER JOIN [DTG].[TableColumn] AS CLM WITH (NOLOCK) 
		ON CLM.TableId = TBL.TableId
	LEFT JOIN DTG.Term AS T WITH (NOLOCK)
		ON T.TermId = CLM.TermId
	 WHERE
		TBL.[TermId] = @TermId AND
		CLM.IsKey = 1