
/* KUWAIT TURKISH PARTICIPATION BANK INC.
*
*  All rights are reserved. Reproduction or transmission in whole or in part, in
*  any form or by any means, electronic, mechanical or otherwise, is prohibited
*  without the prior written consent of the copyright owner.
*
*
*  Generator Information
*		Generator				: BOAContainer
*		Generated By			: karadayi
*		Generated Date			: 11/03/2016 19:56:33
*		File Version			: 1.0
*		Purpose					: <Lütfen açıklama giriniz.>
*		Last Modified By		: karadayi
*		Last Modification Date	: 11/03/2016 19:56:33
*
*/
CREATE PROCEDURE [DTG].[sel_TermRuleByColumns]
(
	@TermId INT = NULL,
	@TemplateType TINYINT = NULL,
	@AlertStatus TINYINT = NULL
)
AS
	SET NOCOUNT ON;
BEGIN

	SELECT
		TermRuleId,
		TermId,
		TemplateType,
		Value,
		AlertStatus
  FROM [DTG].[TermRule] WITH (NOLOCK)
  WHERE (@TermId IS NULL OR TermId = @TermId)
    AND (@TemplateType IS NULL OR TemplateType = @TemplateType)
    AND (@AlertStatus IS NULL OR AlertStatus = @AlertStatus)
    

END