


/*  KUWAIT TURKISH PARTICIPATION BANK INC.
 *   
 *  All rights are reserved. Reproduction or transmission in whole or in part, in          
 *  any form or by any means, electronic, mechanical or otherwise, is prohibited
 *  without the prior written consent of the copyright owner. 
 * 
 * 
 *  Generator Information
 *      Generator				: BOA.Tools.CodeGenerator
 *      Generated By			: karadayi
 *      Generated Date			: 09/03/2016
 *		File Version            : 1.1
 *		Purpose                 : Lütfen doldurunuz.
 *		Last Modified By        : karadayi
 *		Last Modification Date  : 12/06/2016
 *
 */
CREATE PROCEDURE [DTG].[sel_Module]
	@LanguageId TINYINT = 1
AS 
	SET NOCOUNT ON
BEGIN

	SELECT 
			D.ParamCode AS ModuleId, -- DomainId, 
			D.ParamDescription AS ModuleCode, -- DomainName, 
			D.ParamDescription AS [Description] -- DomainName, 
	  FROM [CORParameter].[dbo].[Parameter] AS D WITH (NOLOCK)
	 WHERE 
		D.ParamType = 'BusinessArchitecture' AND 
		D.ParamValue = 1 AND 
		D.LanguageId = @LanguageId
	 ORDER BY D.ParamDescription
/*
	SELECT 
		0 AS ModuleId,
		CASE @LanguageId 
			WHEN 1 THEN 'Genel' 
			ELSE 'General' 
		END AS ModuleCode,
		CASE @LanguageId 
			WHEN 1 THEN 'Genel' 
			ELSE 'General' 
		END AS [Description]
	UNION ALL
	SELECT 
		ParamCode AS ModuleId,
		ParamDescription AS ModuleCode,
		ParamDescription AS [Description]
	 FROM [CORParameter].[dbo].[Parameter] WITH (NOLOCK)
	WHERE
		Paramtype='CapabilityCategory' AND
		LanguageId = @LanguageId
	ORDER BY ModuleCode
*/
END