
/* KUWAIT TURKISH PARTICIPATION BANK INC.
*
*  All rights are reserved. Reproduction or transmission in whole or in part, in
*  any form or by any means, electronic, mechanical or otherwise, is prohibited
*  without the prior written consent of the copyright owner.
*
*
*  Generator Information
*		Generator				: BOAContainer
*		Generated By			: karadayi
*		Generated Date			: 04/03/2016 10:17:29
*		File Version			: 1.0
*		Purpose					: <Lütfen açıklama giriniz.>
*		Last Modified By		: karadayi
*		Last Modification Date	: 04/03/2016 10:17:29
*
*/
CREATE PROCEDURE [DTG].[sel_DataType]
    @DataTypeLanguageId TINYINT = 1,
	@LanguageId TINYINT = 1
AS
	SET NOCOUNT ON;
BEGIN

	IF @DataTypeLanguageId = 0 OR @DataTypeLanguageId IS NULL
	BEGIN
		SELECT
		 D.DataTypeId
		,D.[Name]
		,M.Value
		,L.DataTypeLanguageId
		,L.Name AS DataTypeLanguage
		,0 AS IsTemplateType
      FROM [DTG].[DataType] D WITH (NOLOCK)
	 LEFT JOIN DTG.DataTypeMatch M WITH (NOLOCK)
			ON D.DataTypeId = M.DataTypeId
			AND M.DataTypeLanguageId = @DataTypeLanguageId
	 LEFT JOIN DTG.DataTypeLanguage L WITH (NOLOCK)
	        ON L.DataTypeLanguageId = M.DataTypeLanguageId
	 WHERE D.DataTypeId = -1 -- Boş kayıt getirmesi için
	END
	ELSE
	BEGIN
		SELECT TMP.* INTO #TMP FROM
		(
			SELECT
				 D.DataTypeId
				,CASE @LanguageId
					 WHEN 1 THEN D.[Name]
					 WHEN 2 THEN D.[NameEN]
					 ELSE D.[Name]
				 END AS Name
				,M.Value
				,CASE L.DataTypeLanguageId
				     WHEN NULL THEN @DataTypeLanguageId
					 ELSE L.DataTypeLanguageId
			     END AS DataTypeLanguageId
				,L.Name AS DataTypeLanguage
				,0 AS IsTemplateType
			  FROM [DTG].[DataType] D WITH (NOLOCK)
			  LEFT JOIN DTG.DataTypeMatch M WITH (NOLOCK)
			         ON D.DataTypeId = M.DataTypeId
					 AND M.DataTypeLanguageId = @DataTypeLanguageId
			  LEFT JOIN DTG.DataTypeLanguage L WITH (NOLOCK)
			         ON L.DataTypeLanguageId = M.DataTypeLanguageId
		) AS TMP

		UPDATE #TMP SET DataTypeLanguageId = ISNULL(DataTypeLanguageId, @DataTypeLanguageId)

		SELECT 
			DataTypeId,
			[Name],
			Value,
			DataTypeLanguageId,
			DataTypeLanguage,
			IsTemplateType
		  FROM #TMP
	END
END