
/* KUWAIT TURKISH PARTICIPATION BANK INC.
*
*  All rights are reserved. Reproduction or transmission in whole or in part, in
*  any form or by any means, electronic, mechanical or otherwise, is prohibited
*  without the prior written consent of the copyright owner.
*
*
*  Generator Information
*		Generator				: BOAContainer
*		Generated By			: karadayi
*		Generated Date			: 03/06/2016
*		File Version			: 1.0
*		Purpose					: <Lütfen açıklama giriniz.>
*		Last Modified By		: karadayi
*		Last Modification Date	: 03/06/2016
*
*/
CREATE PROCEDURE [DTG].[sel_TableFromSystemByExistenceInCatalog]
(
	@ServerName VARCHAR(50),
	@DBName VARCHAR(50),
	@SchemaName VARCHAR(20),
	@ExistenceType TINYINT
)
AS
	SET NOCOUNT ON;
BEGIN

DECLARE
	@ExecuteString NVARCHAR(1000),
	@JoinClause NVARCHAR(100),
	@WhereClause NVARCHAR(500)

IF @ExistenceType = 1
BEGIN -- Katalog'da olanlar
	SET @JoinClause = N',BOACatalog.DTG.[Table] TBL WITH (NOLOCK)'
	SET @WhereClause = N'AND sch.name = TBL.SchemaName AND t.name = TBL.TableName'
END
ELSE IF @ExistenceType = 2
BEGIN -- Draft'da olanlar
	SET @JoinClause = N',BOACatalog.DTG.[TableDraft] TBL WITH (NOLOCK)'
	SET @WhereClause = N'AND sch.name = TBL.SchemaName AND t.name = TBL.TableName'
END
ELSE IF @ExistenceType = 3
BEGIN -- Katalog'da ve Draft'da olmayanlar
	SET @JoinClause = N''
	SET @WhereClause = N'AND t.name NOT IN
	(
		SELECT TableName FROM BOACatalog.DTG.[Table] WITH (NOLOCK) WHERE SchemaName = ''' + @SchemaName + '''
		UNION
		SELECT TableName FROM BOACatalog.DTG.[TableDraft] WITH (NOLOCK) WHERE SchemaName = ''' + @SchemaName + '''
	)'
END
ELSE
BEGIN -- Hepsi
	SET @JoinClause = N''
	SET @WhereClause = N''
END

SET @ExecuteString = N'
SELECT
	t.modify_date, 
	t.schema_id SchemaId, 
	t.name ItemName, 
	sch.name SchemaName, 
	t.object_id ObjectId 
  FROM
	[' + @ServerName + '].' + @DBName + '.sys.tables t WITH (NOLOCK),
	[' + @ServerName + '].' + @DBName + '.sys.schemas sch WITH (NOLOCK)
	' + @JoinClause + '
 WHERE
	t.schema_id = sch.schema_id AND 
	sch.name = ''' + @SchemaName + '''
	' + @WhereClause + '
 ORDER BY t.name'

EXECUTE sp_executesql @ExecuteString

END