

/* KUWAIT TURKISH PARTICIPATION BANK INC.
*
*  All rights are reserved. Reproduction or transmission in whole or in part, in
*  any form or by any means, electronic, mechanical or otherwise, is prohibited
*  without the prior written consent of the copyright owner.
*
*
*  Generator Information
*		Generator				: BOAContainer
*		Generated By			: karadayi
*		Generated Date			: 21/03/2018
*		File Version			: 1.0
*		Purpose					: KVKK Kapsamında Veri Silme Taleplerini Karşılayabilmek Adına Müşteri Verilerinin Ne Olduğunu Bulan Sistemin Yönetim Tablosunu Getirir
*		Last Modified By		: karadayi
*		Last Modification Date	: 13/04/2018
*
*/
CREATE PROCEDURE [DTG].[sel_CustomerDataRequest]
(
	@UniqueKeyForCustomer VARCHAR(50) = NULL,
	@IsProcessed TINYINT = NULL
)
AS
SET NOCOUNT ON
BEGIN

  SELECT [CustomerDataRequestId]
		,[UniqueKeyForCustomer]
		,[IsProcessed]
		,[ProcessBeginDate]
		,[ProcessEndDate]
		,[UserName]
		,[HostName]
		,[SystemDate]
		,[UpdateUserName]
		,[UpdateHostName]
		,[UpdateSystemDate]
		,[HostIP]
	FROM [DTG].[CustomerDataRequest] WITH (NOLOCK)
   WHERE (@UniqueKeyForCustomer IS NULL OR UniqueKeyForCustomer = @UniqueKeyForCustomer) AND
	     (@IsProcessed IS NULL OR IsProcessed = @IsProcessed)
	ORDER BY IsProcessed ASC, SystemDate DESC

END