
/* KUWAIT TURKISH PARTICIPATION BANK INC.
*
*  All rights are reserved. Reproduction or transmission in whole or in part, in
*  any form or by any means, electronic, mechanical or otherwise, is prohibited
*  without the prior written consent of the copyright owner.
*
*
*  Generator Information
*		Generator				: BOAContainer
*		Generated By			: karadayi
*		Generated Date			: 17/03/2016 10:17:29
*		File Version			: 1.0
*		Purpose					: <Lütfen açıklama giriniz.>
*		Last Modified By		: sk000880 - Eski workgroup değiştirildi.
*		Last Modification Date	: 08/12/2017
*
*/
CREATE PROCEDURE [DTG].[sel_WorkGroup]
	@WorkGroupType TINYINT = NULL,
	@LanguageId TINYINT = 1
AS
	SET NOCOUNT ON
BEGIN
	
	DECLARE @RootWorkgroupId INT = NULL
	SELECT @RootWorkgroupId = CAST(ParamCode AS INT) FROM [BOA].COR.Parameter WHERE ParamType = 'ITROOTWORKGROUP' AND ParamValue2 = '1'
	

	IF @WorkGroupType = 0 OR @WorkGroupType IS NULL
	BEGIN

	SELECT WorkGroupId, [Name]
		  FROM
		  (
			SELECT WorkGroupId, [Name]
			  FROM BOA.AUT.WorkGroup W WITH (NOLOCK)
			 WHERE W.Type IN('Servis','Departman','Birim')
			   AND IsActive = 1

			UNION

			SELECT DISTINCT wg.WorkGroupId, wg.[Name]
				   FROM BOA.AUT.WorkGroup wg WITH (NOLOCK)
				  INNER JOIN BOA.AUT.WorkGroup wg2 WITH (NOLOCK) 
					ON wg2.ParentId = wg.WorkGroupId
					AND wg2.IsActive = 1
				  WHERE wg.ParentId = @RootWorkgroupId
					AND wg.IsActive = 1

			UNION

			SELECT DISTINCT wg2.WorkGroupId,  wg.[Name] + ' - ' + wg2.[Name] AS [Name]
			FROM BOA.AUT.WorkGroup wg WITH (NOLOCK)
			INNER JOIN BOA.AUT.WorkGroup wg2 WITH (NOLOCK) 
			ON wg2.ParentId = wg.WorkGroupId
			AND wg2.IsActive = 1
			WHERE wg.ParentId = @RootWorkgroupId
			AND wg.IsActive = 1
		  ) AS Container
		  ORDER BY [Name]

	END
	ELSE
	BEGIN

		SELECT WorkGroupId, [Name]
		  FROM
		  (
			 SELECT DISTINCT wg.WorkGroupId, wg.[Name]
			   FROM BOA.AUT.WorkGroup wg WITH (NOLOCK)
			  INNER JOIN BOA.AUT.WorkGroup wg2 WITH (NOLOCK) 
				ON wg2.ParentId = wg.WorkGroupId
				AND wg2.IsActive = 1
			  WHERE wg.ParentId = @RootWorkgroupId
				AND wg.IsActive = 1

			  UNION

			 SELECT DISTINCT wg2.WorkGroupId,  wg.[Name] + ' - ' + wg2.[Name] AS [Name]
			   FROM BOA.AUT.WorkGroup wg WITH (NOLOCK)
			  INNER JOIN BOA.AUT.WorkGroup wg2 WITH (NOLOCK) 
				ON wg2.ParentId = wg.WorkGroupId
				AND wg2.IsActive = 1
			  WHERE wg.ParentId = @RootWorkgroupId
				AND wg.IsActive = 1

			UNION

			SELECT CAST(ParamValue AS INT) AS WorkGroupId, ParamDescription AS [Name]
			  FROM [CORParameter].[dbo].[Parameter] WITH (NOLOCK)
			 WHERE ParamGroupCode = 'DTG'
			   AND ParamType = 'NonITDevelopmentUnit'
			   AND LanguageId = @LanguageId
		  ) AS Container
		  ORDER BY [Name]

	END
END