
/* KUWAIT TURKISH PARTICIPATION BANK INC.
*
*  All rights are reserved. Reproduction or transmission in whole or in part, in
*  any form or by any means, electronic, mechanical or otherwise, is prohibited
*  without the prior written consent of the copyright owner.
*
*
*  Generator Information
*		Generator				: BOAContainer
*		Generated By			: karadayi
*		Generated Date			: 09/03/2016
*		File Version			: 1.0
*		Purpose					: <Lütfen açıklama giriniz.>
*		Last Modified By		: karadayi
*		Last Modification Date	: 09/03/2016
*
*/
CREATE PROCEDURE [DTG].[sel_DataTypeLanguage]
	@LanguageId TINYINT = 1
AS
	SET NOCOUNT ON;
BEGIN

	SELECT [DataTypeLanguageId]
		  ,CASE @LanguageId
			WHEN 1 THEN [Name]
			ELSE [NameEN]
		   END AS Name
	  FROM [DTG].[DataTypeLanguage] WITH (NOLOCK)

END