
/* KUWAIT TURKISH PARTICIPATION BANK INC.
*
*  All rights are reserved. Reproduction or transmission in whole or in part, in
*  any form or by any means, electronic, mechanical or otherwise, is prohibited
*  without the prior written consent of the copyright owner.
*
*
*  Generator Information
*		Generator				: BOAContainer
*		Generated By			: karadayi
*		Generated Date			: 28/09/2016
*		File Version			: 1.0
*		Purpose					: <Lütfen açıklama giriniz.>
*		Last Modified By		: karadayi
*		Last Modification Date	: 20/10/2016
*
*/
CREATE PROCEDURE [DTG].[sel_TableColumnDataMask]
(
	@DBName VARCHAR(20) = NULL,
	@SchemaName VARCHAR(20) = NULL,
	@TableName VARCHAR(50) = NULL,
	@ColumnName VARCHAR(100) = NULL,
	@LanguageId TINYINT = 1
)
AS
	SET NOCOUNT ON
		
	CREATE TABLE #TMP
	(
		TableColumnId INT,
		TermName VARCHAR(200),
		DBName VARCHAR(20),
		SchemaName VARCHAR(20),
		TableName VARCHAR(50),
		ColumnName VARCHAR(100),
		DataType VARCHAR(50),
		DataMaskTypeId TINYINT,
		DataMaskType VARCHAR(50)
	)

	CREATE TABLE #TMP2
	(
		TableColumnId INT,
		TermName VARCHAR(200),
		DBName VARCHAR(20),
		SchemaName VARCHAR(20),
		TableName VARCHAR(50),
		ColumnName VARCHAR(100),
		DataType VARCHAR(50),
		DataMaskTypeId TINYINT,
		DataMaskType VARCHAR(50)
	)

	-- Katalog içerisindeki tablolar
	INSERT INTO #TMP
	SELECT
		TC.TableColumnId,
		T.Name,
		TBL.DBName,
		TBL.SchemaName,
		TBL.TableName,
		TC.ColumnName,
		[DTG].[fConvertDataTypeForDataMaskProcess](TC.DataType) AS DataType,
		DM.[ParamCode] AS DataMaskTypeId,
		DM.[ParamValue] AS DataMaskType
	FROM [DTG].[TableColumn] AS TC WITH (NOLOCK)
	INNER JOIN [DTG].[Table] AS TBL WITH (NOLOCK) ON
		TBL.TableId = TC.TableId
	INNER JOIN [DTG].[Term] AS T WITH (NOLOCK) ON
		T.TermId = TBL.TermId
	INNER JOIN DTG.TermDataMask AS TDM WITH (NOLOCK) ON
		TDM.TermId = T.TermId AND
		TDM.DataType = [DTG].[fConvertDataTypeForDataMaskProcess](TC.DataType)
	LEFT JOIN [CORParameter].[dbo].[Parameter] DM WITH (NOLOCK) 
		ON DM.[ParamCode] = TDM.DataMaskTypeId AND 
		DM.Paramtype='DATAMASK' AND 
		DM.LanguageId = 1
	WHERE 
		(TC.IsReference = 1)
	
	INSERT INTO #TMP
	SELECT
		TC.TableColumnId,
		T.Name,
		TBL.DBName,
		TBL.SchemaName,
		TBL.TableName,
		TC.ColumnName,
		[DTG].[fConvertDataTypeForDataMaskProcess](TC.DataType) AS DataType,
		DM.[ParamCode] AS DataMaskTypeId,
		DM.[ParamValue] AS DataMaskType
	FROM [DTG].[TableColumn] AS TC WITH (NOLOCK)
	INNER JOIN [DTG].[Table] AS TBL WITH (NOLOCK) ON
		TBL.TableId = TC.TableId
	INNER JOIN [DTG].[Term] AS T WITH (NOLOCK) ON
		T.TermId = TC.TermId
	INNER JOIN DTG.TermDataMask AS TDM WITH (NOLOCK) ON
		TDM.TermId = T.TermId AND
		TDM.DataType = [DTG].[fConvertDataTypeForDataMaskProcess](TC.DataType)
	LEFT JOIN [CORParameter].[dbo].[Parameter] DM WITH (NOLOCK) 
		ON DM.[ParamCode] = TDM.DataMaskTypeId AND 
		DM.Paramtype='DATAMASK' AND 
		DM.LanguageId = 1
	WHERE 
	    T.TermId NOT IN(1,3,8)

	-- Taslak içerisindeki tablolar
	INSERT INTO #TMP
	SELECT
		TC.TableColumnDraftId,
		T.Name,
		TBL.DBName,
		TBL.SchemaName,
		TBL.TableName,
		TC.ColumnName,
		[DTG].[fConvertDataTypeForDataMaskProcess](TC.DataType) AS DataType,
		DM.[ParamCode] AS DataMaskTypeId,
		DM.[ParamValue] AS DataMaskType
	FROM [DTG].[TableColumnDraft] AS TC WITH (NOLOCK)
	INNER JOIN [DTG].[TableDraft] AS TBL WITH (NOLOCK) ON
		TBL.TableDraftId = TC.TableDraftId
	INNER JOIN [DTG].[Term] AS T WITH (NOLOCK) ON
		T.TermId = TBL.TermId
	INNER JOIN DTG.TermDataMask AS TDM WITH (NOLOCK) ON
		TDM.TermId = T.TermId AND
		TDM.DataType = [DTG].[fConvertDataTypeForDataMaskProcess](TC.DataType)
	LEFT JOIN [CORParameter].[dbo].[Parameter] DM WITH (NOLOCK) 
		ON DM.[ParamCode] = TDM.DataMaskTypeId AND 
		DM.Paramtype='DATAMASK' AND 
		DM.LanguageId = 1
	WHERE 
		(TC.IsReference = 1)
	
	INSERT INTO #TMP
	SELECT
		TC.TableColumnDraftId,
		T.Name,
		TBL.DBName,
		TBL.SchemaName,
		TBL.TableName,
		TC.ColumnName,
		[DTG].[fConvertDataTypeForDataMaskProcess](TC.DataType) AS DataType,
		DM.[ParamCode] AS DataMaskTypeId,
		DM.[ParamValue] AS DataMaskType
	FROM [DTG].[TableColumnDraft] AS TC WITH (NOLOCK)
	INNER JOIN [DTG].[TableDraft] AS TBL WITH (NOLOCK) ON
		TBL.TableDraftId = TC.TableDraftId
	INNER JOIN [DTG].[Term] AS T WITH (NOLOCK) ON
		T.TermId = TC.TermId
	INNER JOIN DTG.TermDataMask AS TDM WITH (NOLOCK) ON
		TDM.TermId = T.TermId AND
		TDM.DataType = [DTG].[fConvertDataTypeForDataMaskProcess](TC.DataType)
	LEFT JOIN [CORParameter].[dbo].[Parameter] DM WITH (NOLOCK) 
		ON DM.[ParamCode] = TDM.DataMaskTypeId AND 
		DM.Paramtype='DATAMASK' AND 
		DM.LanguageId = 1
	WHERE 
	    T.TermId NOT IN(1,3,8)
	
	-- TableColumnDataMask TableColumnId varolan tablo ile farklı değer içerme olasılığı var
	-- o sebeple TableColumnId ile joinlemiyorum
	INSERT INTO #TMP2
	SELECT
		TC.TableColumnId,
		T.Name,
		TBL.DBName,
		TBL.SchemaName,
		TBL.TableName,
		TC.ColumnName,
		[DTG].[fConvertDataTypeForDataMaskProcess](TC.DataType) AS DataType,
		DM.[ParamCode] AS DataMaskTypeId,
		DM.[ParamValue] AS DataMaskType
	FROM [DTG].[TableColumn] AS TC WITH (NOLOCK)
	INNER JOIN [DTG].[Table] AS TBL WITH (NOLOCK) ON
		TBL.TableId = TC.TableId
	INNER JOIN DTG.TableColumnDataMask AS TCM WITH (NOLOCK) ON
		--TCM.TableColumnId = TC.TableColumnId
		TCM.DBName = TBL.DBName
		AND TCM.SchemaName = TBL.SchemaName
		AND TCM.TableName = TBL.TableName
		AND TCM.ColumnName = TC.ColumnName
	LEFT JOIN [DTG].[Term] AS T WITH (NOLOCK) ON
		T.TermId = TC.TermId
	LEFT JOIN [CORParameter].[dbo].[Parameter] DM WITH (NOLOCK) 
		ON DM.[ParamCode] = TCM.DataMaskTypeId AND 
		DM.Paramtype='DATAMASK' AND 
		DM.LanguageId = 1

	-- TableColumnDataMask'da kayıtlı olanların önceliği var
	-- O sebeple TermDataMask'ta da aynı kolon için kayıt geliyorsa onu ez
	UPDATE #TMP
		SET #TMP.DataMaskTypeId = #TMP2.DataMaskTypeId,
			#TMP.DataMaskType = #TMP2.DataMaskType 
	  FROM #TMP WITH (NOLOCK)
	 INNER JOIN #TMP2 WITH (NOLOCK) ON
		--#TMP.TableColumnId = #TMP2.TableColumnId
		#TMP.DBName = #TMP2.DBName
		AND #TMP.SchemaName = #TMP2.SchemaName
		AND #TMP.TableName = #TMP2.TableName
		AND #TMP.ColumnName = #TMP2.ColumnName

	-- Yukarıda update edilenleri çıkar
	DELETE FROM #TMP2
	WHERE TableColumnId IN
	(SELECT #TMP2.TableColumnId
	  FROM #TMP2 WITH (NOLOCK)
	 INNER JOIN #TMP WITH (NOLOCK) ON
		#TMP.DBName = #TMP2.DBName
		AND #TMP.SchemaName = #TMP2.SchemaName
		AND #TMP.TableName = #TMP2.TableName
		AND #TMP.ColumnName = #TMP2.ColumnName)
	 
	-- TermDataMask'da kaydı olmayan ama maskelenecek bir alan varsa onu da ekle
	INSERT INTO #TMP
	SELECT
		TableColumnId,
		TermName,
		DBName,
		SchemaName,
		TableName,
		ColumnName,
		DataType,
		DataMaskTypeId,
		DataMaskType
	FROM #TMP2
	--WHERE TableColumnId NOT IN (SELECT TableColumnId FROM #TMP)

	 -- Alt ortamlarına aktarımlarda maskelenmesi gereken tablo alanlarının listesi
	 SELECT DISTINCT
		TermName,
		DBName,
		SchemaName,
		TableName,
		ColumnName,
		DataType,
		DataMaskTypeId,
		DataMaskType
	  FROM #TMP
	 ORDER BY DBName, SchemaName, TableName