
/* KUWAIT TURKISH PARTICIPATION BANK INC.
*
*  All rights are reserved. Reproduction or transmission in whole or in part, in
*  any form or by any means, electronic, mechanical or otherwise, is prohibited
*  without the prior written consent of the copyright owner.
*
*
*  Generator Information
*		Generator				: BOAContainer
*		Generated By			: karadayi
*		Generated Date			: 28/04/2016
*		File Version			: 1.0
*		Purpose					: <Lütfen açıklama giriniz.>
*		Last Modified By		: karadayi
*		Last Modification Date	: 28/04/2016
*
*/
CREATE PROCEDURE [DTG].[sel_DataTypeByKey]
	@DataTypeId INT,
    @DataTypeLanguageId TINYINT = 1,
	@LanguageId TINYINT = 1
AS
	SET NOCOUNT ON;
BEGIN

	SELECT
		 D.DataTypeId
		,D.[Name]
		,D.[NameEN]
		,M.Value
		,CASE L.DataTypeLanguageId
				WHEN NULL THEN @DataTypeLanguageId
				ELSE L.DataTypeLanguageId
			END AS DataTypeLanguageId
		,L.Name AS DataTypeLanguage
		,0 AS IsTemplateType
		FROM [DTG].[DataType] D WITH (NOLOCK)
		LEFT JOIN DTG.DataTypeMatch M WITH (NOLOCK)
				ON D.DataTypeId = M.DataTypeId
				AND M.DataTypeLanguageId = @DataTypeLanguageId
		LEFT JOIN DTG.DataTypeLanguage L WITH (NOLOCK)
				ON L.DataTypeLanguageId = M.DataTypeLanguageId
		WHERE D.DataTypeId = @DataTypeId
END