
/* KUWAIT TURKISH PARTICIPATION BANK INC.
*
*  All rights are reserved. Reproduction or transmission in whole or in part, in
*  any form or by any means, electronic, mechanical or otherwise, is prohibited
*  without the prior written consent of the copyright owner.
*
*
*  Generator Information
*		Generator				: BOAContainer
*		Generated By			: karadayi
*		Generated Date			: 11/03/2016 08:18:08
*		File Version			: 1.0
*		Purpose					: <Lütfen açıklama giriniz.>
*		Last Modified By		: karadayi
*		Last Modification Date	: 19/12/2017
*
*/
CREATE PROCEDURE [DTG].[sel_TableColumnByColumns]
@DBName VARCHAR(20) = NULL,
@SchemaName VARCHAR(20) = NULL,
@TableName VARCHAR(50) = NULL,
@TermId INT = NULL,
@IsKey TINYINT = NULL,
@DataTypeChanged TINYINT = NULL,
@Nullable TINYINT = NULL,
@IsReference TINYINT = NULL,
@IsIdentity TINYINT = NULL
AS
	 
SET NOCOUNT ON

	SELECT
		TC.TableColumnId,
		TC.TableId,
		TBL.DBName + '.' + TBL.SchemaName + '.' + TBL.TableName AS TableName,
		TC.TermId,
		T.Name AS TermName,
		T.Level1Domain AS TermLevel1Domain,
		T.Level2Domain AS TermLevel2Domain,
		TC.ColumnName,
		TC.IsKey,
		TC.DataTypeChanged,
		TC.DataType,
		TC.Nullable,
		TC.Sensitivity,
		TC.[Description],
        TC.[IsReference],
        TC.[IsIdentity]
	FROM [DTG].[TableColumn] AS TC WITH (NOLOCK)
	LEFT JOIN DTG.Term AS T WITH (NOLOCK)
		ON T.TermId = TC.TermId
	LEFT JOIN DTG.[Table] AS TBL WITH (NOLOCK)
		ON TBL.TableId = TC.TableId
	WHERE ((@DBName IS NULL) OR TBL.DBName = @DBName) 
		AND ((@SchemaName IS NULL) OR TBL.SchemaName = @SchemaName) 
		AND	((@TableName IS NULL) OR TBL.TableName = @TableName) 
		AND	((@TermId IS NULL) OR TC.TermId = @TermId) 
		AND	((@IsKey IS NULL) OR TC.IsKey = @IsKey) 
		AND	((@DataTypeChanged IS NULL) OR TC.DataTypeChanged = @DataTypeChanged) 
		AND	((@Nullable IS NULL) OR TC.Nullable = @Nullable) 
		AND	((@IsReference IS NULL) OR TC.IsReference = @IsReference) 
		AND	((@IsIdentity IS NULL) OR TC.IsIdentity = @IsIdentity)