
/* KUWAIT TURKISH PARTICIPATION BANK INC.
*
*  All rights are reserved. Reproduction or transmission in whole or in part, in
*  any form or by any means, electronic, mechanical or otherwise, is prohibited
*  without the prior written consent of the copyright owner.
*
*
*  Generator Information
*		Generator				: BOAContainer
*		Generated By			: karadayi
*		Generated Date			: 10/07/2018
*		File Version			: 1.0
*		Purpose					: <Lütfen açıklama giriniz.>
*		Last Modified By		: karadayi
*		Last Modification Date	: 27/07/2018
*
*/
CREATE PROCEDURE [DTG].[sel_ScriptDefinition]
@ScriptDefinitionId INT = NULL,
@ScriptGroup VARCHAR(50) = NULL
AS
SET NOCOUNT ON
BEGIN
   SELECT [ScriptDefinitionId]
      ,[ScriptText]
      ,[ScriptTag]
      ,[ScriptGroup]
      ,[SortOrder]
      ,[UserName]
      ,[HostName]
      ,[SystemDate]
      ,[UpdateUserName]
      ,[UpdateHostName]
      ,[UpdateSystemDate]
      ,[HostIP]
	 FROM DTG.ScriptDefinition WITH (NOLOCK)
	WHERE
		(@ScriptDefinitionId IS NULL OR [ScriptDefinitionId] = @ScriptDefinitionId) AND
		(@ScriptGroup IS NULL OR [ScriptGroup] = @ScriptGroup)
END