
/* KUWAIT TURKISH PARTICIPATION BANK INC.
*
*  All rights are reserved. Reproduction or transmission in whole or in part, in
*  any form or by any means, electronic, mechanical or otherwise, is prohibited
*  without the prior written consent of the copyright owner.
*
*
*  Generator Information
*		Generator				: BOAContainer
*		Generated By			: karadayi
*		Generated Date			: 29/06/2016
*		File Version			: 1.0
*		Purpose					: <Lütfen açıklama giriniz.>
*		Last Modified By		: karadayi
*		Last Modification Date	: 02/12/2016
*
*/
CREATE PROCEDURE [DTG].[sel_DBNameFromCatalog]
AS
	SET NOCOUNT ON

	SELECT DISTINCT
		TBL.DBName
	FROM [DTG].[Table] AS TBL WITH (NOLOCK)
	UNION
	SELECT DISTINCT
		TBL.DBName
	FROM [DTG].[TableDraft] AS TBL WITH (NOLOCK)
	ORDER BY TBL.DBName