
/* KUWAIT TURKISH PARTICIPATION BANK INC.
*
*  All rights are reserved. Reproduction or transmission in whole or in part, in
*  any form or by any means, electronic, mechanical or otherwise, is prohibited
*  without the prior written consent of the copyright owner.
*
*
*  Generator Information
*		Generator				: BOAContainer
*		Generated By			: karadayi
*		Generated Date			: 03/03/2016 10:17:29
*		File Version			: 1.0
*		Purpose					: <Lütfen açıklama giriniz.>
*		Last Modified By		: karadayi
*		Last Modification Date	: 03/03/2016 10:17:29
*
*/
CREATE PROCEDURE [DTG].[sel_DataTemplate]
	@LanguageId TINYINT = 1
AS
	SET NOCOUNT ON;
BEGIN

	SELECT -1 TermId, CASE @LanguageId WHEN 1 THEN 'Yok' else 'None' END AS Name
	UNION
	SELECT T.TermId, CASE @LanguageId WHEN 1 THEN Name else NameEN END AS Name
	FROM DTG.Term T WITH (NOLOCK)
	INNER JOIN DTG.TermRule TR WITH (NOLOCK) ON TR.TermId = T.TermId
	WHERE TR.TemplateType = 3 AND TR.Value = '1' AND TR.AlertStatus = 1
	ORDER BY Name
END