

/* KUWAIT TURKISH PARTICIPATION BANK INC.
*
*  All rights are reserved. Reproduction or transmission in whole or in part, in
*  any form or by any means, electronic, mechanical or otherwise, is prohibited
*  without the prior written consent of the copyright owner.
*
*
*  Generator Information
*		Generator				: BOAContainer
*		Generated By			: karadayi
*		Generated Date			: 19/12/2017
*		File Version			: 1.0
*		Purpose					: <Lütfen açıklama giriniz.>
*		Last Modified By		: 
*		Last Modification Date	: 
*
*/
CREATE PROCEDURE [DTG].[sel_DataInventoryManagement]
@ParamType VARCHAR(20),
@ParamCode VARCHAR(20),
@LanguageId TINYINT = 1
AS
SET NOCOUNT ON
BEGIN
	DECLARE 
		@ExecuteString NVARCHAR(500),
		@SpName VARCHAR(50),
		@Params VARCHAR(50)

	SELECT 
		@SpName = ParamValue2
       ,@Params = 
		CASE WHEN ParamValue3 IS NULL 
			THEN + ''
		ELSE REPLACE(ParamValue3, '{0}', CAST(@LanguageId AS VARCHAR)) END
	FROM BOACatalog.DTG.Parameter WITH (NOLOCK)
	WHERE
		ParamType = @ParamType AND
		ParamCode = @ParamCode AND
		LanguageId = @LanguageId

	SET @ExecuteString = N'EXEC ' + @SpName + ' ' + @Params
	EXECUTE sp_executesql @ExecuteString
END