
/* KUWAIT TURKISH PARTICIPATION BANK INC.
*
*  All rights are reserved. Reproduction or transmission in whole or in part, in
*  any form or by any means, electronic, mechanical or otherwise, is prohibited
*  without the prior written consent of the copyright owner.
*
*
*  Generator Information
*		Generator				: BOAContainer
*		Generated By			: karadayi
*		Generated Date			: 03/03/2016 10:24:20
*		File Version			: 1.0
*		Purpose					: <Lütfen açıklama giriniz.>
*		Last Modified By		: karadayi
*		Last Modification Date	: 03/03/2016 10:24:20
*
*/
CREATE PROCEDURE [DTG].[sel_TemplateType]
AS
	SET NOCOUNT ON;
BEGIN

	SELECT
		TemplateTypeId,
		[Description]
	FROM [DTG].[TemplateType] WITH (NOLOCK)
	ORDER BY TemplateTypeId

END