
/* KUWAIT TURKISH PARTICIPATION BANK INC.
*
*  All rights are reserved. Reproduction or transmission in whole or in part, in
*  any form or by any means, electronic, mechanical or otherwise, is prohibited
*  without the prior written consent of the copyright owner.
*
*
*  Generator Information
*		Generator				: BOAContainer
*		Generated By			: smevis
*		Generated Date			: 09/09/2016 14:00:00
*		File Version			: 1.0
*		Purpose					: Check if the selected entity is already linked to a table.
*		Last Modified By		: smevis
*		Last Modification Date	: 09/09/2016 14:00:00
*
*/

CREATE PROCEDURE [DTG].[sel_TermHasLinkedTable]
	@TermId INT = NULL
AS
	SET NOCOUNT ON;

	SELECT 1 AS Result FROM [DTG].[Table] WITH (NOLOCK) WHERE TermId = @TermId

	UNION ALL

	SELECT 1 AS Result FROM [DTG].[TableDraft] WITH (NOLOCK) WHERE TermId = @TermId