
/* KUWAIT TURKISH PARTICIPATION BANK INC.
*
*  All rights are reserved. Reproduction or transmission in whole or in part, in
*  any form or by any means, electronic, mechanical or otherwise, is prohibited
*  without the prior written consent of the copyright owner.
*
*
*  Generator Information
*		Generator				: BOAContainer
*		Generated By			: karadayi
*		Generated Date			: 09/06/2016 15:20:01
*		File Version			: 1.0
*		Purpose					: <Lütfen açıklama giriniz.>
*		Last Modified By		: karadayi
*		Last Modification Date	: 13/06/2016 16:45
*
*/
CREATE PROCEDURE [DTG].[sel_ColumnRule]
AS
	SET NOCOUNT ON;

	SELECT
		CR.ColumnRuleId,
		T.TermId,
		T.Name AS TermName,
		CR.DataType,
		CR.ColumnName
	FROM [DTG].[ColumnRule] AS CR WITH (NOLOCK)
	INNER JOIN DTG.Term AS T WITH (NOLOCK) ON
		T.TermId = CR.TermId