
/* KUWAIT TURKISH PARTICIPATION BANK INC.
*
*  All rights are reserved. Reproduction or transmission in whole or in part, in
*  any form or by any means, electronic, mechanical or otherwise, is prohibited
*  without the prior written consent of the copyright owner.
*
*
*  Generator Information
*		Generator				: BOAContainer
*		Generated By			: karadayi
*		Generated Date			: 11/03/2016 08:18:08
*		File Version			: 1.0
*		Purpose					: <Lütfen açıklama giriniz.>
*		Last Modified By		: karadayi
*		Last Modification Date	: 15/06/2016
*
*/
CREATE PROCEDURE [DTG].[sel_TableColumn]
AS
	SET NOCOUNT ON

	SELECT
		TC.TableColumnId,
		TC.TableId,
		TC.TermId,
		T.Name AS TermName,
		T.Level1Domain AS TermLevel1Domain,
		T.Level2Domain AS TermLevel2Domain,
		TC.ColumnName,
		TC.IsKey,
		TC.DataTypeChanged,
		TC.DataType,
		TC.Nullable,
		TC.Sensitivity,
		TC.[Description],
        TC.[IsReference],
        TC.[IsIdentity]
	FROM [DTG].[TableColumn] AS TC WITH (NOLOCK)
	LEFT JOIN DTG.Term AS T WITH (NOLOCK)
		ON T.TermId = TC.TermId