

/* KUWAIT TURKISH PARTICIPATION BANK INC.
*
*  All rights are reserved. Reproduction or transmission in whole or in part, in
*  any form or by any means, electronic, mechanical or otherwise, is prohibited
*  without the prior written consent of the copyright owner.
*
*
*  Generator Information
*		Generator				: BOAContainer
*		Generated By			: karadayi
*		Generated Date			: 14/04/2016 16:28:21
*		File Version			: 1.0
*		Purpose					: <Lütfen açıklama giriniz.>
*		Last Modified By		: karadayi
*		Last Modification Date	: 16/15/2016 16:28:21
*
*/
CREATE PROCEDURE [DTG].[sel_TermCodeByModuleId]
	@ModuleId VARCHAR(5) = NULL
AS
	SET NOCOUNT ON
BEGIN

	DECLARE
		@NumericCode VARCHAR(30),
		--@TermCode VARCHAR(30),
		--@Abbreviation VARCHAR(3),
		@MaxId INT

	--IF @ModuleId = '0'
	--BEGIN
	--	SELECT @Abbreviation = 'GEN'
	--END
	--ELSE
	--BEGIN
	--	SELECT @Abbreviation = ParamValue
	--	  FROM [CORParameter].[dbo].[Parameter] WITH (NOLOCK)
	--	 WHERE Paramtype='CapabilityCategory'
	--			AND ParamCode = @ModuleId
	--END

	SELECT @MaxId = MAX(TermId)
      FROM [DTG].[Term] WITH (NOLOCK)

	SELECT @NumericCode = CAST((@MaxId + 1) AS VARCHAR)
		
	--WHILE LEN(@NumericCode) < 5
	--BEGIN
	--	SET @NumericCode = '0' + @NumericCode
	--END

	--SELECT @TermCode = @Abbreviation + @NumericCode

	--SELECT @TermCode AS TermCode

	SELECT @NumericCode AS TermCode

END