
/* KUWAIT TURKISH PARTICIPATION BANK INC.
*
*  All rights are reserved. Reproduction or transmission in whole or in part, in
*  any form or by any means, electronic, mechanical or otherwise, is prohibited
*  without the prior written consent of the copyright owner.
*
*
*  Generator Information
*		Generator				: BOAContainer
*		Generated By			: karadayi
*		Generated Date			: 15/03/2016 08:46:45
*		File Version			: 1.0
*		Purpose					: <Lütfen açıklama giriniz.>
*		Last Modified By		: karadayi
*		Last Modification Date	: 30/11/2017 
*
*/

CREATE PROCEDURE [DTG].[sel_TableDraftByColumns]
(
	@DBName VARCHAR(20),
	@SchemaName VARCHAR(20),
	@TableName VARCHAR(50) = NULL
)
AS
	SET NOCOUNT ON

	SELECT
		TBL.TableDraftId,
		TBL.DBName,
		TBL.SchemaName,
		TBL.TableName,
		TBL.TermId,
		T.Name AS TermName,
		T.Description AS TermDescription, 
		T.Level1Domain AS TermLevel1Domain,
		T.Level2Domain AS TermLevel2Domain,
		TBL.IsEntity,
		TBL.[Description],
		TBL.[Status],
		TBL.UserName,
		TBL.UpdateUserName,
		TBL.DevVersion,
		TBL.TestVersion,
		TBL.PrepVersion,
		TBL.ProdVersion,
		TBL.LogTableName,
		TBL.TableType,
		TBL.DevelopmentLocation
  FROM [DTG].[TableDraft] AS TBL WITH (NOLOCK)
	LEFT JOIN DTG.Term AS T WITH (NOLOCK)
		ON T.TermId = TBL.TermId
  WHERE TBL.DBName = @DBName 
  	AND TBL.SchemaName = @SchemaName 
  	AND ((@TableName IS NULL) OR TBL.TableName = @TableName)