
/* KUWAIT TURKISH PARTICIPATION BANK INC.
*
*  All rights are reserved. Reproduction or transmission in whole or in part, in
*  any form or by any means, electronic, mechanical or otherwise, is prohibited
*  without the prior written consent of the copyright owner.
*
*
*  Generator Information
*		Generator				: BOAContainer
*		Generated By			: karadayi
*		Generated Date			: 30/03/2016 21:52:29
*		File Version			: 1.0
*		Purpose					: <Lütfen açıklama giriniz.>
*		Last Modified By		: karadayi
*		Last Modification Date	: 04/10/2017
*
*/
CREATE PROCEDURE [DTG].[sel_TableScript]
(
	@DBName VARCHAR(20) = NULL,
	@SchemaName VARCHAR(3) = NULL,
	@TableName VARCHAR(100) = NULL
)
AS
	SET NOCOUNT ON

	SELECT TDP.TableDesignPackageId, TDP.Script, TDP.[Version], TBL.TestVersion, TDP.SystemDate, TDP.UpdateSystemDate
      FROM [DTG].[TableDesignPackage] TDP WITH (NOLOCK)
	  INNER JOIN DTG.[Table] TBL WITH (NOLOCK)
		ON TBL.DBName = TDP.DBName
		AND TBL.SchemaName = TDP.SchemaName
		AND TBL.TableName = TDP.TableName
		AND TBL.[Status] = 1
     WHERE (@DBName IS NULL OR TDP.DBName = @DBName)
       AND (@SchemaName IS NULL OR TDP.SchemaName = @SchemaName)
       AND (@TableName IS NULL OR TDP.TableName = @TableName)
       AND TDP.[Status] = 1
     ORDER BY TDP.TableDesignPackageId