
/* KUWAIT TURKISH PARTICIPATION BANK INC.
*
*  All rights are reserved. Reproduction or transmission in whole or in part, in
*  any form or by any means, electronic, mechanical or otherwise, is prohibited
*  without the prior written consent of the copyright owner.
*
*
*  Generator Information
*		Generator				: BOAContainer
*		Generated By			: karadayi
*		Generated Date			: 03/08/2016
*		File Version			: 1.0
*		Purpose					: <Lütfen açıklama giriniz.>
*		Last Modified By		: karadayi
*		Last Modification Date	: 03/08/2016
*
*/
CREATE PROCEDURE [DTG].[sel_TableVersion]
(
	@DBName VARCHAR(20),
	@SchemaName VARCHAR(3),
	@TableName VARCHAR(100)
)
AS
	
SET NOCOUNT ON

	SELECT DevVersion, TestVersion, PrepVersion, ProdVersion
      FROM  DTG.[Table] TBL WITH (NOLOCK)
     WHERE TBL.DBName = @DBName
		AND TBL.SchemaName = @SchemaName
		AND TBL.TableName = @TableName
		AND TBL.[Status] = 1