
/*
*
*
*  Generator Information
*		Generator				: BOAContainer
*		Generated By			: tp.keremc
*		Generated Date			: 26/08/2020
*		File Version			: 1.0
*		Purpose					: 
*		Last Modified By		: tp.keremc
*		Last Modification Date	: 26/08/2020
*
*/
CREATE PROCEDURE [DTG].[sel_SensitivityForBusinessDictionary]

AS
	SET NOCOUNT ON
	
	SELECT
		 S.SensitivityId
		,S.Name
		,S.LanguageId
	 FROM [BOACatalog].[DTG].[Sensitivity] S WITH (NOLOCK)
	 WHERE S.LanguageId = 1