
/* KUWAIT TURKISH PARTICIPATION BANK INC.
*
*  All rights are reserved. Reproduction or transmission in whole or in part, in
*  any form or by any means, electronic, mechanical or otherwise, is prohibited
*  without the prior written consent of the copyright owner.
*
*
*  Generator Information
*		Generator				: BOAContainer
*		Generated By			: karadayi
*		Generated Date			: 29/06/2016
*		File Version			: 1.0
*		Purpose					: <Lütfen açıklama giriniz.>
*		Last Modified By		: karadayi
*		Last Modification Date	: 09/01/2018
*
*/
CREATE PROCEDURE [DTG].[sel_TableColumnInformationSecurityByColumns]
(
	@DBName VARCHAR(20) = NULL,
	@SchemaName VARCHAR(20) = NULL,
	@TableName VARCHAR(50) = NULL,
	@LanguageId TINYINT = 1
)
AS
	SET NOCOUNT ON;

	SELECT
		TC.TableColumnId,
		TC.TableId,
		TBL.DBName,
		TBL.SchemaName,
		TBL.TableName,
		TC.ColumnName,
		TC.DataType,
		S.ParamCode AS SensitivityId,
		S.ParamValue AS Sensitivity,
		DM.[ParamCode] AS DataMaskTypeId,
		DM.[ParamValue] AS DataMaskType,
		TCM.SubsetCriteria,
		TCM.SubsetOperator
	FROM [DTG].[TableColumn] AS TC WITH (NOLOCK)
	INNER JOIN [DTG].[Table] AS TBL WITH (NOLOCK) ON
		TBL.TableId = TC.TableId
	LEFT JOIN DTG.TableColumnDataMask AS TCM WITH (NOLOCK) ON
		TCM.DBName = TBL.DBName
		AND TCM.SchemaName = TBL.SchemaName
		AND TCM.TableName = TBL.TableName
		AND TCM.ColumnName = TC.ColumnName
	LEFT JOIN DTG.vParameter S WITH (NOLOCK) ON
		S.ParamGroupCode = 'DTG' AND
		S.ParamType = 'SENSITIVITY' AND
		TC.Sensitivity = S.ParamCode AND 
		S.LanguageId = @LanguageId
	LEFT JOIN DTG.vParameter DM WITH (NOLOCK) 
		ON DM.[ParamCode] = TCM.DataMaskTypeId AND 
		DM.Paramtype='DATAMASK' AND 
		DM.LanguageId = @LanguageId
	WHERE 
		((@DBName IS NULL) OR 
			TBL.DBName = @DBName) AND
        ((@SchemaName IS NULL) OR
			TBL.SchemaName = @SchemaName) AND
		((@TableName IS NULL) OR
			TBL.TableName = @TableName)

UNION

    SELECT
		TC.TableColumnDraftId AS TableColumnDraftId,
		TC.TableDraftId AS TableId,
		TBL.DBName,
		TBL.SchemaName,
		TBL.TableName,
		TC.ColumnName,
		TC.DataType,
		S.ParamCode AS SensitivityId,
		S.ParamValue AS Sensitivity,
		DM.[ParamCode] AS DataMaskTypeId,
		DM.[ParamValue] AS DataMaskType,
		TCM.SubsetCriteria,
		TCM.SubsetOperator
	FROM [DTG].[TableColumnDraft] AS TC WITH (NOLOCK)
	INNER JOIN [DTG].[TableDraft] AS TBL WITH (NOLOCK) ON
		TBL.TableDraftId = TC.TableDraftId
	LEFT JOIN DTG.TableColumnDataMask AS TCM WITH (NOLOCK) ON
		TCM.DBName = TBL.DBName
		AND TCM.SchemaName = TBL.SchemaName
		AND TCM.TableName = TBL.TableName
		AND TCM.ColumnName = TC.ColumnName
	LEFT JOIN DTG.vParameter S WITH (NOLOCK) ON
		S.ParamGroupCode = 'DTG' AND
		S.ParamType = 'SENSITIVITY' AND
		TC.Sensitivity = S.ParamCode AND 
		S.LanguageId = @LanguageId
	LEFT JOIN DTG.vParameter DM WITH (NOLOCK) 
		ON DM.[ParamCode] = TCM.DataMaskTypeId AND 
		DM.Paramtype='DATAMASK' AND 
		DM.LanguageId = @LanguageId
	WHERE 
		((@DBName IS NULL) OR 
			TBL.DBName = @DBName) AND
        ((@SchemaName IS NULL) OR
			TBL.SchemaName = @SchemaName) AND
		((@TableName IS NULL) OR
			TBL.TableName = @TableName)