

/* KUWAIT TURKISH PARTICIPATION BANK INC.
*
*  All rights are reserved. Reproduction or transmission in whole or in part, in
*  any form or by any means, electronic, mechanical or otherwise, is prohibited
*  without the prior written consent of the copyright owner.
*
*
*  Generator Information
*		Generator				: BOAContainer
*		Generated By			: karadayi
*		Generated Date			: 20/07/2016
*		File Version			: 1.0
*		Purpose					: <Lütfen açıklama giriniz.>
*		Last Modified By		: karadayi
*		Last Modification Date	: 02/05/2018
*
*/
CREATE PROCEDURE [DTG].[sel_TermDataMaskByTermId]
(
	@TermId INT,
	@LanguageId TINYINT = 1
)
AS
	SET NOCOUNT ON

	SELECT
		TDM.TermId,
		TDM.DataType,
		TDM.DataMaskTypeId,
		DM.[ParamValue] AS DataMaskType,
		CASE 
			WHEN TDM.IsActive IS NULL THEN 1 
			ELSE TDM.IsActive 
		END AS IsActive
	  FROM [DTG].[TermDataMask] AS TDM WITH (NOLOCK)
	 INNER JOIN DTG.vParameter DM WITH (NOLOCK) 
		ON DM.[ParamCode] = TDM.DataMaskTypeId AND 
		DM.Paramtype='DATAMASK' AND 
		DM.LanguageId = @LanguageId
	WHERE TDM.TermId = @TermId