/* KUWAIT TURKISH PARTICIPATION BANK INC.
*
*  All rights are reserved. Reproduction or transmission in whole or in part, in
*  any form or by any means, electronic, mechanical or otherwise, is prohibited
*  without the prior written consent of the copyright owner.
*
*
*  Generator Information
*		Generator				: BOAContainer
*		Generated By			: karadayi
*		Generated Date			: 26/09/2017
*		File Version			: 1.0
*		Purpose					: Kullanıcıya ait kavramların kaçına metin yazarları tarafından metin önerilmiş bilgisi döner.
*		Last Modified By		: karadayi
*		Last Modification Date	: 09/10/2017
*
*/
CREATE PROCEDURE [DTG].[sel_RecommendedTextCountByUserName]
	@UserName VARCHAR(10)
AS
SET NOCOUNT ON
BEGIN

	DECLARE 
		@Count INT = 0,
		@IsActive VARCHAR(5) = NULL

	-- Parametre Tablosundan Mesajın Görünüp Görünmeyeceği Bilgisi Alınır
	SELECT @IsActive = ParamValue
	  FROM [CORParameter].[dbo].[Parameter] WITH (NOLOCK)
	 WHERE ParamType = 'TextRecInfoMsg' 
	   AND ParamCode = 'Activation'
	   AND ParamGroupCode = 'DTG'

	IF (@IsActive IS NOT NULL) AND UPPER(@IsActive) = 'TRUE'
	BEGIN
		SELECT @Count = COUNT(1)
		  FROM DTG.Term AS T WITH (NOLOCK)
		 INNER JOIN BOA.COR.BoaUser AS BU WITH (NOLOCK) ON T.UserName = BU.UserCode
		 -- Kullanıcı hala aynı serviste çalışıyor ise getir
         INNER JOIN BOA.AUT.AccessPoint AS AP WITH (NOLOCK) on T.DataManager = AP.WorkgroupId
		   AND AP.UserId = BU.UserId
		 WHERE T.UserName = @UserName
		   AND T.CopyWriterApproval IN(1, 3) -- Text Recommended and Detailed Info Requested
	END

	SELECT @Count AS RecommendedTextCount
END