
/* KUWAIT TURKISH PARTICIPATION BANK INC.
*
*  All rights are reserved. Reproduction or transmission in whole or in part,C. in
*  any form or by any means,C. electronic,C. mechanical or otherwise,C. is prohibited
*  without the prior written consent of the copyright owner.
*
*
*  Generator Information
*		Generator				: BOAContainer
*		Generated By			: karadayi
*		Generated Date			: 21/03/2018
*		File Version			: 1.0
*		Purpose					: KVKK Kapsamında Veri Silme Taleplerini Karşılayabilmek Adına Müşteri Verilerinin Ne Olduğunu Bulan Sistemin Yönetim Tablosunu Detayını Getirir
*		Last Modified By		: karadayi
*		Last Modification Date	: 13/04/2018
*
*/
CREATE PROCEDURE [DTG].[sel_CustomerDataRequestDetail]
(
	@CustomerDataRequestId INT
)
AS
SET NOCOUNT ON
BEGIN

	SELECT C.[CustomerDataRequestDetailId]
		  ,C.[CustomerDataRequestId]
		  ,C.[TermId]
		  ,T.[Name] AS TermName
		  ,C.[SearchValue]
		  ,C.[UserName]
		  ,C.[HostName]
		  ,C.[SystemDate]
		  ,C.[UpdateUserName]
		  ,C.[UpdateHostName]
		  ,C.[UpdateSystemDate]
		  ,C.[HostIP]
	  FROM [DTG].[CustomerDataRequestDetail] AS C WITH (NOLOCK)
	 INNER JOIN [DTG].Term AS T WITH (NOLOCK) ON T.TermId = C.TermId
     WHERE [CustomerDataRequestId] = @CustomerDataRequestId

END