
/* KUWAIT TURKISH PARTICIPATION BANK INC.
*
*  All rights are reserved. Reproduction or transmission in whole or in part, in
*  any form or by any means, electronic, mechanical or otherwise, is prohibited
*  without the prior written consent of the copyright owner.
*
*
*  Generator Information
*		Generator				: BOAContainer
*		Generated By			: karadayi
*		Generated Date			: 12/04/2016 16:28:21
*		File Version			: 1.0
*		Purpose					: <Lütfen açıklama giriniz.>
*		Last Modified By		: karadayi
*		Last Modification Date	: 04/05/2018
*
*/
CREATE PROCEDURE [DTG].[sel_TermFromTableKeyColumn]
(
	@TermId INT,
	@LanguageId TINYINT = 1
)
AS
	SET NOCOUNT ON;

	DECLARE @KeyColumnTermId INT

	SELECT @KeyColumnTermId = CLM.TermId
	  FROM [DTG].[Table] AS TBL WITH (NOLOCK)
	 INNER JOIN [DTG].[TableColumn] AS CLM WITH (NOLOCK) 
		ON CLM.TableId = TBL.TableId
	 WHERE
		TBL.[TermId] = @TermId
		AND CLM.IsKey = 1

	EXECUTE [DTG].[sel_TermByKey] @KeyColumnTermId,	@LanguageId