
/* KUWAIT TURKISH PARTICIPATION BANK INC.
*
*  All rights are reserved. Reproduction or transmission in whole or in part, in
*  any form or by any means, electronic, mechanical or otherwise, is prohibited
*  without the prior written consent of the copyright owner.
*
*
*  Generator Information
*		Generator				: BOAContainer
*		Generated By			: karadayi
*		Generated Date			: 15/03/2016 08:18:08
*		File Version			: 1.0
*		Purpose					: <Lütfen açıklama giriniz.>
*		Last Modified By		: karadayi
*		Last Modification Date	: 22/06/2017
*
*/
CREATE PROCEDURE [DTG].[sel_TableColumnDraftByTableId]
(
	@TableDraftId INT,
	@LanguageId TINYINT = 1
 )
AS
	SET NOCOUNT ON;

	SELECT
		TCD.TableColumnDraftId,
		TCD.TableDraftId,
		TCD.TermId,
		T.Name AS TermName,
		T.Description AS TermDescription,
		T.Level1Domain AS TermLevel1Domain,
		T.Level2Domain AS TermLevel2Domain,
		TCD.ColumnName,
		TCD.IsKey,
		TCD.DataTypeChanged,
		TCD.DataType,
		TCD.Nullable,
		S.ParamCode AS SensitivityId,
		S.ParamValue AS Sensitivity,
		TCD.[Description],
        TCD.[IsReference],
        TCD.[IsIdentity],
		TCD.TableColumnCatalogId,
		Inf.ParamValue AS InformationType,
		Inf.ParamCode AS InformationTypeId,
		ow.[Name] AS DataOwner,
		mn.[Name] AS DataManager
	FROM [DTG].[TableColumnDraft] AS TCD WITH (NOLOCK)
	LEFT JOIN DTG.Term AS T WITH (NOLOCK) ON 
		T.TermId = TCD.TermId
	LEFT JOIN [CORParameter].[dbo].[Parameter] Inf WITH (NOLOCK) ON
		Inf.ParamGroupCode = 'DTG' AND
		Inf.ParamType = 'INFORMATIONTYPE' AND
		T.[Type] = Inf.ParamCode and
		Inf.LanguageId = @LanguageId
	LEFT JOIN [CORParameter].[dbo].[Parameter] S WITH (NOLOCK) ON
		S.ParamGroupCode = 'DTG' AND
		S.ParamType = 'SENSITIVITY' AND
		T.Sensitivity = S.ParamCode AND 
		S.LanguageId = @LanguageId
	LEFT JOIN [BOA].[AUT].[WorkGroup] ow WITH (NOLOCK) 
			ON ow.[WorkGroupId] = T.DataOwner
	LEFT JOIN [BOA].[AUT].[WorkGroup] mn WITH (NOLOCK) 
			ON mn.[WorkGroupId] = T.DataManager
	WHERE TCD.TableDraftId = @TableDraftId