
/* KUWAIT TURKISH PARTICIPATION BANK INC.
*
*  All rights are reserved. Reproduction or transmission in whole or in part, in
*  any form or by any means, electronic, mechanical or otherwise, is prohibited
*  without the prior written consent of the copyright owner.
*
*
*  Generator Information
*		Generator				: BOAContainer
*		Generated By			: karadayi
*		Generated Date			: 03/03/2016 10:22:20
*		File Version			: 1.0
*		Purpose					: <Lütfen açıklama giriniz.>
*		Last Modified By		: karadayi
*		Last Modification Date	: 03/03/2016 10:22:20
*
*/
CREATE PROCEDURE [DTG].[sel_TermRules]
@TermId INT,
@LanguageId TINYINT = 1
AS
	SET NOCOUNT ON;
BEGIN

	DECLARE
		@Yes VARCHAR(5),
		@No VARCHAR(5)

	IF @LanguageId = 1
	BEGIN
		SET @Yes = 'EVET'
		SET @No = 'HAYIR'
	END
	ELSE
	BEGIN
		SET @Yes = 'YES'
		SET @No = 'NO'
	END

	SELECT  DISTINCT
		 T.TermId
		,CASE TR1.[Value] 
			WHEN '1' THEN @Yes 
			ELSE @No 
		 END AS IsTemplateDataType
		,CASE TR1.[Value] 
			WHEN '1' THEN 'True' 
			ELSE 'False' 
		 END AS IsTemplateDataTypeBoolean
		,CASE TR2.[Value] 
			WHEN '1' THEN @Yes 
			ELSE @No 
		 END AS IfDataTypeInconsistencyExists
		,CASE TR2.[Value] 
			WHEN '1' THEN 'True' 
			ELSE 'False' 
		 END AS IfDataTypeInconsistencyExistsBoolean
		,DT.DataTypeId
		,CASE @LanguageId 
			WHEN 1 THEN DT.[Name] 
			WHEN 2 THEN DT.[NameEN] 
			ELSE DT.[Name] 
		 END AS DataType
		,TR5.[Value] ValueSet
		,TR6.[Value] TableColumnName
	  FROM [DTG].[Term] T WITH (NOLOCK)
	  LEFT JOIN [DTG].[TermRule] TR WITH (NOLOCK) 
		ON TR.TermId = T.TermId
	  LEFT JOIN [DTG].[TermRule] TR1 WITH (NOLOCK) 
		ON TR1.[TermId] = TR.[TermId] 
		AND  TR1.TemplateType = 1 
		AND TR1.AlertStatus = 1
	  LEFT JOIN [DTG].[TermRule] TR2 WITH (NOLOCK) 
		ON TR2.[TermId] = TR.[TermId] 
		AND  TR2.TemplateType = 2 
		AND TR2.AlertStatus = 1
	  LEFT JOIN [DTG].[TermRule] TR3 WITH (NOLOCK) 
		ON TR3.[TermId] = TR.[TermId] 
		AND  TR3.TemplateType = 3 
		AND TR3.AlertStatus = 1
	  LEFT JOIN [DTG].[DataType] DT WITH (NOLOCK) 
		ON DT.DataTypeId = TR3.Value
	  LEFT JOIN [DTG].[TermRule] TR5 WITH (NOLOCK) 
		ON TR5.[TermId] = TR.[TermId] 
		AND  TR5.TemplateType = 4 
		AND TR5.AlertStatus = 1
	  LEFT JOIN [DTG].[TermRule] TR6 WITH (NOLOCK) 
		ON TR6.[TermId] = TR.[TermId] 
		AND  TR6.TemplateType = 5 
		AND TR6.AlertStatus = 1
	WHERE T.TermId = @TermId

END