
/* KUWAIT TURKISH PARTICIPATION BANK INC.
*
*  All rights are reserved. Reproduction or transmission in whole or in part, in
*  any form or by any means, electronic, mechanical or otherwise, is prohibited
*  without the prior written consent of the copyright owner.
*
*
*  Generator Information
*		Generator				: BOAContainer
*		Generated By			: karadayi
*		Generated Date			: 09/05/2017
*		File Version			: 1.0
*		Purpose					: <Lütfen açıklama giriniz.>
*		Last Modified By		: karadayi
*		Last Modification Date	: 09/05/2017
*
*/
CREATE PROCEDURE [DTG].[sel_TableDataMaskExceptionByColumns]
(
	@DBName VARCHAR(20) = NULL,
	@SchemaName VARCHAR(20) = NULL,
	@TableName VARCHAR(50) = NULL
)
AS
	SET NOCOUNT ON;

	SELECT
		TBL.DBName,
		TBL.SchemaName,
		TBL.TableName,
		(CASE WHEN E.TableName IS NULL THEN 0 ELSE 1 END) AS IsExceptional
	FROM [DTG].[Table] AS TBL WITH (NOLOCK)
	LEFT JOIN DTG.TableDataMaskException AS E WITH (NOLOCK) ON
		E.DBName = TBL.DBName
		AND E.SchemaName = TBL.SchemaName
		AND E.TableName = TBL.TableName
	WHERE 
		((@DBName IS NULL) OR 
			TBL.DBName = @DBName) AND
        ((@SchemaName IS NULL) OR
			TBL.SchemaName = @SchemaName) AND
		((@TableName IS NULL) OR
			TBL.TableName = @TableName)

UNION

	SELECT
		TBL.DBName,
		TBL.SchemaName,
		TBL.TableName,
		(CASE WHEN E.TableName IS NULL THEN 0 ELSE 1 END) AS IsExceptional
	FROM [DTG].[TableDraft] AS TBL WITH (NOLOCK)
	LEFT JOIN DTG.TableDataMaskException AS E WITH (NOLOCK) ON
		E.DBName = TBL.DBName
		AND E.SchemaName = TBL.SchemaName
		AND E.TableName = TBL.TableName
	WHERE 
		((@DBName IS NULL) OR 
			TBL.DBName = @DBName) AND
        ((@SchemaName IS NULL) OR
			TBL.SchemaName = @SchemaName) AND
		((@TableName IS NULL) OR
			TBL.TableName = @TableName)