/*  KUWAIT TURKISH PARTICIPATION BANK INC.
 *   
 *  All rights are reserved. Reproduction or transmission in whole or in part, in          
 *  any form or by any means, electronic, mechanical or otherwise, is prohibited
 *  without the prior written consent of the copyright owner. 
 * 
 * 
 *  Generator Information
 *      Generator				: BOA.Tools.CodeGenerator
 *      Generated By			: karadayi
 *      Generated Date			: 02/06/2016
 *		File Version            : 1.1
 *		Purpose                 : Lütfen doldurunuz.
 *		Last Modified By        : karadayi
 *		Last Modification Date  : 11.06.2018
 *
 */
CREATE PROCEDURE [DTG].[sel_BusinessDomain]
	@DomainLevel TINYINT = NULL,
	@ParentDomainId INT = NULL,
	@LanguageId TINYINT = 1
AS 
	SET NOCOUNT ON

	SELECT 
			D.ParamCode AS DomainId, 
			D.ParamDescription AS DomainName, 
			D.ParamValue AS DomainLevel, 
			D.ParamValue2 AS ParentDomainId,
			P.ParamDescription AS ParentDomainName, 
			P.ParamValue AS ParentDomainLevel
	  INTO #TMP
	  FROM BOACatalog.DTG.vParameter AS D WITH (NOLOCK)
	  LEFT JOIN BOACatalog.DTG.vParameter AS P WITH (NOLOCK)
		ON P.ParamCode = D.ParamValue2 
		AND P.ParamType = 'BusinessArchitecture'
		AND P.LanguageId = @LanguageId
	 WHERE 
		D.ParamType = 'BusinessArchitecture' 
		AND D.LanguageId = @LanguageId
		AND D.ParamValue < 3
		AND ((@DomainLevel IS NULL) OR D.ParamValue = @DomainLevel)
		AND ((@ParentDomainId IS NULL) OR D.ParamValue2 = @ParentDomainId)

	 UPDATE #TMP SET DomainId = NULL WHERE DomainId = ''
	 UPDATE #TMP SET DomainLevel = NULL WHERE DomainLevel = ''
	 UPDATE #TMP SET ParentDomainId = NULL WHERE ParentDomainId = ''
	 UPDATE #TMP SET ParentDomainLevel = NULL WHERE ParentDomainLevel = ''

	 SELECT DomainId, DomainName, DomainLevel, 
			CASE DomainLevel 
				WHEN 1 THEN NULL
				ELSE ParentDomainId
			END AS ParentDomainId,
			ParentDomainName, ParentDomainLevel
	   FROM #TMP
	 ORDER BY DomainLevel, DomainName