
/* KUWAIT TURKISH PARTICIPATION BANK INC.
*
*  All rights are reserved. Reproduction or transmission in whole or in part, in
*  any form or by any means, electronic, mechanical or otherwise, is prohibited
*  without the prior written consent of the copyright owner.
*
*
*  Generator Information
*		Generator				: BOAContainer
*		Generated By			: karadayi
*		Generated Date			: 23/03/2016
*		File Version			: 1.0
*		Purpose					: <Lütfen açıklama giriniz.>
*		Last Modified By		: karadayi
*		Last Modification Date	: 23/03/2016
*
*/
CREATE PROCEDURE [DTG].[sel_TemplateDataType]
    @DataTypeLanguageId TINYINT = 1,
	@LanguageId TINYINT = 1
AS
	SET NOCOUNT ON;
BEGIN

	SELECT TMP.* INTO #TMP FROM
		(
			SELECT
				 T.TermId AS DataTypeId
				,CASE @LanguageId
					WHEN 1 THEN T.Name
					WHEN 2 THEN T.NameEN
					ELSE T.[Name]
				 END AS Name
				,M.Value
				,CASE L.DataTypeLanguageId
					WHEN NULL THEN @DataTypeLanguageId
					ELSE L.DataTypeLanguageId
				 END AS DataTypeLanguageId
				,L.Name AS DataTypeLanguage
				,1 AS IsTemplateType
			  FROM DTG.Term T WITH (NOLOCK)
			 INNER JOIN DTG.TermRule TR WITH (NOLOCK)
					ON TR.TermId = T.TermId
			 LEFT JOIN DTG.DataTypeMatch M WITH (NOLOCK)
					ON T.TermId = M.DataTypeId
				   AND M.DataTypeLanguageId = @DataTypeLanguageId
			 LEFT JOIN DTG.DataTypeLanguage L WITH (NOLOCK)
					ON L.DataTypeLanguageId = M.DataTypeLanguageId
			 WHERE
				TR.TemplateType = 1
				AND (
						TR.Value = '1'
						OR Upper(TR.Value) = 'T'
						OR Upper(TR.Value) = 'TRUE'
					)
				AND TR.AlertStatus = 1

			UNION

			SELECT 
				 T.TermId AS DataTypeId
				,CASE @LanguageId 
					WHEN 1 THEN T.Name 
					WHEN 2 THEN T.NameEN 
					ELSE T.[Name] 
				 END AS Name
				,NULL AS Value
				,NULL AS DataTypeLanguageId
				,NULL AS DataTypeLanguage
				,0 AS IsTemplateType
			  FROM DTG.Term T WITH (NOLOCK)
			  WHERE
				[Type] = 0
		) AS TMP

		UPDATE #TMP SET DataTypeLanguageId = ISNULL(DataTypeLanguageId, @DataTypeLanguageId)

		SELECT 
			DataTypeId, 
			[Name], 
			Value, 
			DataTypeLanguageId, 
			DataTypeLanguage, 
			IsTemplateType
		  FROM #TMP
		 ORDER BY Name
END