

/* KUWAIT TURKISH PARTICIPATION BANK INC.
*
*  All rights are reserved. Reproduction or transmission in whole or in part, in
*  any form or by any means, electronic, mechanical or otherwise, is prohibited
*  without the prior written consent of the copyright owner.
*
*
*  Generator Information
*		Generator				: BOAContainer
*		Generated By			: karadayi
*		Generated Date			: 03/06/2016
*		File Version			: 1.0
*		Purpose					: <Lütfen açıklama giriniz.>
*		Last Modified By		: karadayi
*		Last Modification Date	: 29/06/2017
*
*/
CREATE PROCEDURE [DTG].[sel_TermTableRelationByTermId]
(
	@TermId INT
)
AS
	SET NOCOUNT ON

	SELECT 
		T.TermId,
		T.Name AS TermName,
		TBL.TableId,
		TBL.TableName,
		TBL.SchemaName,
		TBL.DBName,
		CLM.TableColumnId,
		CLM.ColumnName,
		0 AS IsDraft,
		T.Level1Domain AS TableLevel1Domain,
		T.Level2Domain AS TableLevel2Domain,
		CLM.TermId AS TableColumnTermId,
		T2.Type AS TableColumnTermType,
		T2.Name AS TableColumnTermName,
		T2.Level1Domain AS TableColumnLevel1Domain,
		T2.Level2Domain AS TableColumnLevel2Domain,
		CLM.IsKey AS TableColumnIsKey,
		CLM.IsIdentity AS TableColumnIsIdentity,
		CLM.IsReference AS TableColumnIsReference,
		TBL.TermId As TableTermId,
		T.Name AS TableTermName,
		CLM.DataType AS ColumnDataType
	  FROM [DTG].[Term] AS T WITH (NOLOCK)
	  INNER JOIN [DTG].[Table] AS TBL WITH (NOLOCK) ON
		TBL.TermId = T.TermId
	  LEFT JOIN DTG.TableColumn AS CLM WITH (NOLOCK) ON
		CLM.TableId = TBL.TableId
	  LEFT JOIN DTG.[Term] AS T2 WITH (NOLOCK) ON
		CLM.TermId = T2.TermId
	 WHERE
		T.[TermId] = @TermId
		--AND CLM.IsReference = 1
		--OR T.BaseTermId = @TermId -- Başka bir Term'i Base alan Term direkt olarak tabloya bağlı olmamalı. Mesela 'Müşteri' den türemiş 'Ödeyen Müşteri' Kavramı da COR.Account tablosunu işret ettiği için başka tabloyu işret etmiyor olmalı.

	UNION

	SELECT 
		T.TermId,
		T.Name AS TermName,
		TBL.TableId,
		TBL.TableName,
		TBL.SchemaName,
		TBL.DBName,
		CLM.TableColumnId,
		CLM.ColumnName,
		0 AS IsDraft,
		T2.Level1Domain AS TableLevel1Domain,
		T2.Level2Domain AS TableLevel2Domain,
		CLM.TermId AS TableColumnTermId,
		T.Type AS TableColumnTermType,
		T.Name AS TableColumnTermName,
		T.Level1Domain AS TableColumnLevel1Domain,
		T.Level2Domain AS TableColumnLevel2Domain,
		CLM.IsKey AS TableColumnIsKey,
		CLM.IsIdentity AS TableColumnIsIdentity,
		CLM.IsReference AS TableColumnIsReference,
		TBL.TermId As TableTermId,
		T2.Name AS TableTermName,
		CLM.DataType AS ColumnDataType
	  FROM [DTG].[Term] AS T WITH (NOLOCK)
	  INNER JOIN [DTG].TableColumn AS CLM WITH (NOLOCK) ON
		CLM.TermId = T.TermId
	  LEFT JOIN DTG.[Table] AS TBL WITH (NOLOCK) ON
		TBL.TableId = CLM.TableId
	  LEFT JOIN DTG.[Term] AS T2 WITH (NOLOCK) ON
		TBL.TermId = T2.TermId
	 WHERE
		T.[TermId] = @TermId
		OR T.BaseTermId = @TermId

	UNION

	SELECT 
		T.TermId,
		T.Name AS TermName,
		TBL.TableDraftId AS TableId,
		TBL.TableName,
		TBL.SchemaName,
		TBL.DBName,
		CLM.TableColumnDraftId AS TableColumnId,
		CLM.ColumnName,
		1 AS IsDraft,
		T.Level1Domain AS TableLevel1Domain,
		T.Level2Domain AS TableLevel2Domain,
		CLM.TermId AS TableColumnTermId,
		T2.Type AS TableColumnTermType,
		T2.Name AS TableColumnTermName,
		T2.Level1Domain AS TableColumnLevel1Domain,
		T2.Level2Domain AS TableColumnLevel2Domain,
		CLM.IsKey AS TableColumnIsKey,
		CLM.IsIdentity AS TableColumnIsIdentity,
		CLM.IsReference AS TableColumnIsReference,
		TBL.TermId As TableTermId,
		T.Name AS TableTermName,
		CLM.DataType AS ColumnDataType
	  FROM [DTG].[Term] AS T WITH (NOLOCK)
	  INNER JOIN [DTG].[TableDraft] AS TBL WITH (NOLOCK) ON
		TBL.TermId = T.TermId
	  LEFT JOIN DTG.[TableColumnDraft] AS CLM WITH (NOLOCK) ON
		CLM.TableDraftId = TBL.TableDraftId
	  LEFT JOIN DTG.[Term] AS T2 WITH (NOLOCK) ON
		CLM.TermId = T2.TermId
	 WHERE
		T.[TermId] = @TermId
		--AND CLM.IsReference = 1
		--OR T.BaseTermId = @TermId -- Başka bir Term'i Base alan Term direkt olarak tabloya bağlı olmamalı. Mesela 'Müşteri' den türemiş 'Ödeyen Müşteri' Kavramı da COR.Account tablosunu işret ettiği için başka tabloyu işret etmiyor olmalı.

	UNION

	SELECT 
		T.TermId,
		T.Name AS TermName,
		TBL.TableDraftId AS TableId,
		TBL.TableName,
		TBL.SchemaName,
		TBL.DBName,
		CLM.TableColumnDraftId AS TableColumnId,
		CLM.ColumnName,
		1 AS IsDraft,
		T2.Level1Domain AS TableLevel1Domain,
		T2.Level2Domain AS TableLevel2Domain,
		CLM.TermId AS TableColumnTermId,
		T.Type AS TableColumnTermType,
		T.Name AS TableColumnTermName,
		T.Level1Domain AS TableColumnLevel1Domain,
		T.Level2Domain AS TableColumnLevel2Domain,
		CLM.IsKey AS TableColumnIsKey,
		CLM.IsIdentity AS TableColumnIsIdentity,
		CLM.IsReference AS TableColumnIsReference,
		TBL.TermId As TableTermId,
		T2.Name AS TableTermName,
		CLM.DataType AS ColumnDataType
	  FROM [DTG].[Term] AS T WITH (NOLOCK)
	  INNER JOIN [DTG].[TableColumnDraft] AS CLM WITH (NOLOCK) ON
		CLM.TermId = T.TermId
	  LEFT JOIN DTG.[TableDraft] AS TBL WITH (NOLOCK) ON
		TBL.TableDraftId = CLM.TableDraftId
	  LEFT JOIN DTG.[Term] AS T2 WITH (NOLOCK) ON
		TBL.TermId = T2.TermId
	 WHERE
		T.[TermId] = @TermId
		OR T.BaseTermId = @TermId