
/* KUWAIT TURKISH PARTICIPATION BANK INC.
*
*  All rights are reserved. Reproduction or transmission in whole or in part, in
*  any form or by any means, electronic, mechanical or otherwise, is prohibited
*  without the prior written consent of the copyright owner.
*
*
*  Generator Information
*		Generator				: BOAContainer
*		Generated By			: smevis
*		Generated Date			: 24/11/2016 12:00:00
*		File Version			: 1.0
*		Purpose				: DB'deki log tablolarını katalogdaki tablolar ile ilişkilendirir.
*		Last Modified By		: smevis
*		Last Modification Date	: 24/11/2016 12:00:00
*		TODO					: Kolon bazlı eşleştirme yapılacak. Eş olmayanları ilişkilendirmeyecek.
*/

CREATE PROCEDURE [DTG].[tsk_LinkLogTable]
AS
    SET NOCOUNT ON;
	
	--Log tablo ismi alanında BOALog db ismi yazmayan ve whitespace karakter içeren verileri düzeltir
	UPDATE boacatalog.dtg.[table] SET LogTableName =NULL WHERE LogTableName =''
	UPDATE boacatalog.dtg.[tabledraft] SET LogTableName =NULL WHERE LogTableName =''

	UPDATE boacatalog.dtg.[table] SET LogTableName = 'BOALog.'+ LogTableName 
	WHERE LogTableName IS NOT NULL AND LogTableName <> '' AND SUBSTRING(LogTableName, 1, 6) <> 'BOALog' 

	UPDATE boacatalog.dtg.[tabledraft] SET LogTableName = 'BOALog.'+ LogTableName 
	WHERE LogTableName IS NOT NULL AND LogTableName <> '' AND SUBSTRING(LogTableName, 1, 6) <> 'BOALog' 
	-----------------------------------

	--Table ve TableDraft tablolarının hepsini distinct yapıp al
    SELECT DISTINCT [Tables] 
    INTO #TempLogTables
    FROM (
	   SELECT t.SchemaName+'.'+t.TableName+'Log' AS [Tables]
	   FROM DTG.[Table] t WITH(NOLOCK) WHERE t.LogTableName IS NULL

	   UNION ALL

	   SELECT td.SchemaName+'.'+td.TableName+'Log' AS [Tables]
	   FROM DTG.[TableDraft] td WITH(NOLOCK) WHERE td.LogTableName IS NULL
    ) as TempLogTables

    --Mevcut Log tablolarını al
    SELECT t.TABLE_SCHEMA+'.'+t.TABLE_NAME AS [TableName] 
    INTO #LogTables
    FROM BOALog.INFORMATION_SCHEMA.TABLES t WITH(NOLOCK)

    --Table ve TableDraft teki tabloların log tablosu olanlarını bir yere al
    SELECT* 
    INTO #MustUpdateLogColumnsOfTableAndTableDraft
    FROM #LogTables lta 
    WHERE lta.TableName in (SELECT * FROM #TempLogTables)


    --Update Table
    UPDATE T1
    SET T1.LogTableName = ('BOALog'+'.'+T2.TableName)
    FROM #MustUpdateLogColumnsOfTableAndTableDraft AS T2 
    INNER JOIN DTG.[Table]  AS T1 WITH(NOLOCK)
    ON (T1.SchemaName+'.'+T1.TableName+'Log')  = T2.TableName

    --Update TableDraft
    UPDATE T1
    SET T1.LogTableName = ('BOALog'+'.'+T2.TableName)
    FROM #MustUpdateLogColumnsOfTableAndTableDraft AS T2 
    INNER JOIN DTG.[TableDraft] AS T1 WITH(NOLOCK)
    ON (T1.SchemaName+'.'+T1.TableName+'Log')  = T2.TableName