/* KUWAIT TURKISH PARTICIPATION BANK INC.
*
*  All rights are reserved. Reproduction or transmission in whole or in part, in
*  any form or by any means, electronic, mechanical or otherwise, is prohibited
*  without the prior written consent of the copyright owner.
*
*
*  Generator Information
*		Generator				: BOAContainer
*		Generated By			: karadayi
*		Generated Date			: 
*		File Version			: 1.0
*		Purpose					: <Lütfen açıklama giriniz.>
*		Last Modified By		: karadayi
*		Last Modification Date	: 13/11/2017
*
*/
CREATE PROCEDURE [DTG].[upd_ValidateByBusinessUnit]
(
	@TermId INT,
	@Name VARCHAR(200),
	@ValidatedByBusinessUnit TINYINT = 1,
	@NameEN VARCHAR(200) = NULL,
	@Description VARCHAR(2000),
	@DescriptionEN VARCHAR(2000) = NULL,
	@UpdateUserName VARCHAR(10) = NULL,
	@UpdateHostName VARCHAR(20) = NULL,
	@HostIP VARCHAR(15) = NULL
)
AS
SET NOCOUNT ON
BEGIN

	DECLARE
		@OldName VARCHAR(200),
		@OldNameEN VARCHAR(200),
		@OldDescription VARCHAR(2000),
		@OldDescriptionEN VARCHAR(2000)

	SELECT @OldName = [Name], @OldNameEN = NameEN, @OldDescription = [Description],	@OldDescriptionEN = DescriptionEN
	  FROM [DTG].[Term] WITH (NOLOCK)
	 WHERE TermId = @TermId

	UPDATE [DTG].[Term] 
	   SET
		ValidatedByBusinessUnit = @ValidatedByBusinessUnit,
		Name = @Name,
		NameEN = @NameEN,
		[Description] = @Description,
		DescriptionEN = @DescriptionEN,
		UpdateUserName = @UpdateUserName,
		UpdateHostName = @UpdateHostName,
		UpdateSystemDate = GETDATE(),
		HostIP = @HostIP
	WHERE TermId = @TermId

	IF ((@Name <> @OldName) OR (@NameEN <> @OldNameEN) OR (@Description <> @OldDescription) OR (@DescriptionEN <> @OldDescriptionEN))
	BEGIN
		UPDATE [DTG].[Term] 
	       SET CopyWriterApproval = 0
		 WHERE TermId = @TermId
	END

END