
/* KUWAIT TURKISH PARTICIPATION BANK INC.
*
*  All rights are reserved. Reproduction or transmission in whole or in part, in
*  any form or by any means, electronic, mechanical or otherwise, is prohibited
*  without the prior written consent of the copyright owner.
*
*
*  Generator Information
*		Generator				: BOAContainer
*		Generated By			: karadayi
*		Generated Date			: 21/03/2018
*		File Version			: 1.0
*		Purpose					: KVKK Kapsamında Veri Silme Taleplerini Karşılayabilmek Adını Müşteri Verilerinin Ne Olduğunu Bulan Sistemin Yönetim Tablosunu Günceller
*		Last Modified By		: karadayi
*		Last Modification Date	: 21/03/2018
*
*/
CREATE PROCEDURE [DTG].[upd_CustomerDataRequest]
(
	@CustomerDataRequestId INT,
	@IsProcessed TINYINT,
	@UpdateUserName VARCHAR(10) = NULL,
	@UpdateHostName VARCHAR(20) = NULL,
	@HostIP VARCHAR(15) = NULL
)
AS
SET NOCOUNT ON
BEGIN
	UPDATE [DTG].[CustomerDataRequest]
	   SET [IsProcessed] = @IsProcessed
		  ,UpdateUserName = @UpdateUserName
		  ,UpdateHostName = @UpdateHostName
		  ,UpdateSystemDate = GETDATE()
		  ,HostIP = @HostIP
	 WHERE CustomerDataRequestId = @CustomerDataRequestId
END