
/* KUWAIT TURKISH PARTICIPATION BANK INC.
*
*  All rights are reserved. Reproduction or transmission in whole or in part, in
*  any form or by any means, electronic, mechanical or otherwise, is prohibited
*  without the prior written consent of the copyright owner.
*
*
*  Generator Information
*		Generator				: BOAContainer
*		Generated By			: karadayi
*		Generated Date			: 02/03/2016 16:28:21
*		File Version			: 1.0
*		Purpose					: <Lütfen açıklama giriniz.>
*		Last Modified By		: karadayi
*		Last Modification Date	: 04/04/2018
*
*/
CREATE PROCEDURE [DTG].[upd_Term]
(
	@TermId INT,
	@TermCode VARCHAR(30),
	@Name VARCHAR(200),
	@NameEN VARCHAR(200) = NULL,
	@Description VARCHAR(2000),
	@DescriptionEN VARCHAR(2000) = NULL,
	@ModuleId INT = NULL,
	@Level1Domain INT = NULL,
	@Level2Domain INT = NULL,
	@Type TINYINT,
	@DataOwner INT,
	@DataManager INT,
	@DataSteward INT = NULL,
	@BaseTermId INT = NULL,
	@Sensitivity TINYINT,
	@Accessibility TINYINT,
	@Integrity TINYINT,
	@IsBusinessUnitTerm TINYINT = 0,
	@UpdateUserName VARCHAR(10) = NULL,
	@UpdateHostName VARCHAR(20) = NULL,
	@HostIP VARCHAR(15) = NULL
)
AS
SET NOCOUNT ON
BEGIN

	DECLARE
		@OldName VARCHAR(200),
		@OldNameEN VARCHAR(200),
		@OldDescription VARCHAR(2000),
		@OldDescriptionEN VARCHAR(2000),
		@CopyWriterApproval TINYINT = NULL

	SELECT @OldName = [Name], @OldNameEN = NameEN, @OldDescription = [Description],	@OldDescriptionEN = DescriptionEN
	  FROM [DTG].[Term] WITH (NOLOCK)
	 WHERE TermId = @TermId	

	IF ((@Name <> @OldName) OR (@NameEN <> @OldNameEN) OR (@Description <> @OldDescription) OR (@DescriptionEN <> @OldDescriptionEN))
	BEGIN
		SET @CopyWriterApproval = 0
	END

	UPDATE [DTG].[Term] 
	   SET
		TermCode = CAST(TermId AS VARCHAR),
		[Name] = @Name,
		NameEN = @NameEN,
		[Description] = @Description,
		DescriptionEN = @DescriptionEN,
		ModuleId = @ModuleId,
		Level1Domain = @Level1Domain,
		Level2Domain = @Level2Domain,
		[Type] = @Type,
		DataOwner = @DataOwner,
		DataManager = @DataManager,
		DataSteward = @DataSteward,
		BaseTermId = @BaseTermId,
		Sensitivity = CASE WHEN @Sensitivity IS NULL THEN Sensitivity ELSE @Sensitivity END,
		Accessibility = CASE WHEN @Accessibility IS NULL THEN Accessibility ELSE @Accessibility END,
		Integrity = CASE WHEN @Integrity IS NULL THEN Integrity ELSE @Integrity END,
		IsBusinessUnitTerm = @IsBusinessUnitTerm,
		CopyWriterApproval = ISNULL(@CopyWriterApproval, CopyWriterApproval),
		UpdateUserName = @UpdateUserName,
		UpdateHostName = @UpdateHostName,
		UpdateSystemDate = GETDATE(),
		HostIP = @HostIP
	WHERE TermId = @TermId

END