
/* KUWAIT TURKISH PARTICIPATION BANK INC.
*
*  All rights are reserved. Reproduction or transmission in whole or in part, in
*  any form or by any means, electronic, mechanical or otherwise, is prohibited
*  without the prior written consent of the copyright owner.
*
*
*  Generator Information
*		Generator				: BOAContainer
*		Generated By			: karadayi
*		Generated Date			: 20/03/2016 21:52:29
*		File Version			: 1.0
*		Purpose					: <Lütfen açıklama giriniz.>
*		Last Modified By		: karadayi
*		Last Modification Date	: 29/11/2017
*
*/
CREATE PROCEDURE [DTG].[upd_TableDesignPackage]
(
	@TableDesignPackageId INT,
	@DevelopmentLocation VARCHAR(50) = NULL,
	@DBName VARCHAR(50) = NULL,
	@SchemaName VARCHAR(20) = NULL,
	@TableName VARCHAR(100) = NULL,
	@RejectReason VARCHAR(MAX) = NULL,
	@Script VARCHAR(MAX) = NULL,
	@Status TINYINT = NULL,
	@UpdateUserName VARCHAR(10) = NULL,
	@UpdateHostName VARCHAR(20) = NULL,
	@HostIP VARCHAR(15) = NULL
)
AS
	 
SET NOCOUNT ON
BEGIN

	UPDATE [DTG].[TableDesignPackage] 
	   SET
		DBName = @DBName,
		SchemaName = @SchemaName,
		TableName = @TableName,
		RejectReason = @RejectReason,
		Script = @Script,
		[Status] = @Status,
		UpdateUserName = @UpdateUserName,
		UpdateHostName = @UpdateHostName,
		HostIP = @HostIP,
		UpdateSystemDate = GETDATE(),
		DevelopmentLocation = ISNULL(@DevelopmentLocation, DevelopmentLocation)
	WHERE TableDesignPackageId = @TableDesignPackageId

END