
/* KUWAIT TURKISH PARTICIPATION BANK INC.
*
*  All rights are reserved. Reproduction or transmission in whole or in part, in
*  any form or by any means, electronic, mechanical or otherwise, is prohibited
*  without the prior written consent of the copyright owner.
*
*
*  Generator Information
*		Generator				: BOAContainer
*		Generated By			: karadayi
*		Generated Date			: 16/08/2016
*		File Version			: 1.0
*		Purpose					: <Lütfen açıklama giriniz.>
*		Last Modified By		: karadayi
*		Last Modification Date	: 17/08/2016
*
*/
CREATE PROCEDURE [DTG].[upd_TableVersion]
(
	@TableId INT,
	@DevVersion TINYINT,
	@TestVersion TINYINT,
	@PrepVersion TINYINT,
	@ProdVersion TINYINT
)
AS
	
SET NOCOUNT ON

	UPDATE [DTG].[Table]
	   SET DevVersion = @DevVersion
		,TestVersion = @TestVersion
		,PrepVersion = @PrepVersion
		,ProdVersion = @ProdVersion
	WHERE TableId = @TableId