

/* KUWAIT TURKISH PARTICIPATION BANK INC.
*
*  All rights are reserved. Reproduction or transmission in whole or in part, in
*  any form or by any means, electronic, mechanical or otherwise, is prohibited
*  without the prior written consent of the copyright owner.
*
*
*  Generator Information
*		Generator				: BOAContainer
*		Generated By			: karadayi
*		Generated Date			: 03/03/2016 10:17:29
*		File Version			: 1.0
*		Purpose					: <Lütfen açıklama giriniz.>
*		Last Modified By		: karadayi
*		Last Modification Date	: 03/03/2016 10:17:29
*
*/
CREATE PROCEDURE [DTG].[upd_TermRules]
(
	@TermId INT,
	@IsTemplateDataType VARCHAR(10) = '0',
	@IfDataTypeInconsistencyExists VARCHAR(10) = '0',
	@DataTemplate VARCHAR(200) = NULL,
	@ValueSet VARCHAR(200) = NULL,
	@TableColumnName VARCHAR(50) = NULL
)
AS
	SET NOCOUNT ON;
BEGIN

	--1	Şablon veri tipi mi?
	UPDATE DTG.TermRule
	   SET Value = @IsTemplateDataType
	 WHERE TermId = @TermId AND TemplateType = 1 

	--2	Şablon veri tipi uyuşmazlığı var mı?
	UPDATE DTG.TermRule
	   SET Value = @IfDataTypeInconsistencyExists
	 WHERE TermId = @TermId AND TemplateType = 2 

	--3	Veri şablonu
	UPDATE DTG.TermRule
	   SET Value = @DataTemplate
	 WHERE TermId = @TermId AND TemplateType = 3 

	--4	Değer seti
	UPDATE DTG.TermRule
	   SET Value = @ValueSet
	 WHERE TermId = @TermId AND TemplateType = 4

	--5	Tablo kolon adı
	UPDATE DTG.TermRule
	   SET Value = @TableColumnName
	 WHERE TermId = @TermId AND TemplateType = 5
END