
/* KUWAIT TURKISH PARTICIPATION BANK INC.
*
*  All rights are reserved. Reproduction or transmission in whole or in part, in
*  any form or by any means, electronic, mechanical or otherwise, is prohibited
*  without the prior written consent of the copyright owner.
*
*
*  Generator Information
*		Generator				: BOAContainer
*		Generated By			: karadayi
*		Generated Date			: 15/04/2016
*		File Version			: 1.0
*		Purpose					: <Lütfen açıklama giriniz.>
*		Last Modified By		: karadayi
*		Last Modification Date	: 15/04/2016
*
*/
CREATE PROCEDURE [DTG].[upd_BaseTermRule]
(
	@TermId INT = NULL,
	@Value VARCHAR(200)
)
AS
	SET NOCOUNT ON;
BEGIN

	UPDATE [DTG].[TermRule]
	   SET
		Value = @Value
	 WHERE
		TermId = @TermId
		AND TemplateType = 1

END