
/* KUWAIT TURKISH PARTICIPATION BANK INC.
*
*  All rights are reserved. Reproduction or transmission in whole or in part, in
*  any form or by any means, electronic, mechanical or otherwise, is prohibited
*  without the prior written consent of the copyright owner.
*
*
*  Generator Information
*		Generator				: BOAContainer
*		Generated By			: karadayi
*		Generated Date			: 09/06/2016
*		File Version			: 1.0
*		Purpose					: <Lütfen açıklama giriniz.>
*		Last Modified By		: karadayi
*		Last Modification Date	: 18/01/2018
*
*/
CREATE PROCEDURE [DTG].[upd_TableDraft]
(
	@TableDraftId INT,
	@DBName VARCHAR(50),
	@SchemaName VARCHAR(20),
	@TableName VARCHAR(50),
	@TermId INT = NULL,
	@Description VARCHAR(500) = NULL,
	@Status TINYINT,
	@UpdateUserName VARCHAR(10) = NULL,
	@UpdateHostName VARCHAR(20) = NULL,
	@HostIP VARCHAR(15) = NULL,
	@DevVersion TINYINT = NULL,
	@TestVersion TINYINT = NULL,
	@PrepVersion TINYINT = NULL,
	@ProdVersion TINYINT = NULL,
	@LogTableName VARCHAR(100) = NULL,
	@TableType TINYINT = NULL,
	@DevelopmentLocation VARCHAR(50) = NULL
)
AS
	SET NOCOUNT ON

	UPDATE [DTG].[TableDraft] SET
		DBName = @DBName,
		SchemaName = @SchemaName,
		TableName = @TableName,
		TermId = @TermId,
		[Description] = @Description,
		[Status] = @Status,
		UpdateUserName = @UpdateUserName,
		UpdateHostName = @UpdateHostName,
		UpdateSystemDate = GETDATE(),
		HostIP = @HostIP,
		DevVersion = ISNULL(@DevVersion, DevVersion),
		TestVersion = ISNULL(@TestVersion, TestVersion),
		PrepVersion = ISNULL(@PrepVersion, PrepVersion),
		ProdVersion = ISNULL(@ProdVersion, ProdVersion),
		LogTableName = ISNULL(@LogTableName, LogTableName),
		TableType = ISNULL(@TableType, TableType),
		DevelopmentLocation = ISNULL(@DevelopmentLocation, DevelopmentLocation)
	WHERE TableDraftId = @TableDraftId