
/* KUWAIT TURKISH PARTICIPATION BANK INC.
*
*  All rights are reserved. Reproduction or transmission in whole or in part, in
*  any form or by any means, electronic, mechanical or otherwise, is prohibited
*  without the prior written consent of the copyright owner.
*
*
*  Generator Information
*		Generator				: BOAContainer
*		Generated By			: karadayi
*		Generated Date			: 10/07/2018
*		File Version			: 1.0
*		Purpose					: <Lütfen açıklama giriniz.>
*		Last Modified By		: karadayi
*		Last Modification Date	: 27/07/2018
*
*/
CREATE PROCEDURE [DTG].[upd_ScriptDefinition]
@ScriptDefinitionId INT
,@ScriptText VARCHAR(5000)
,@ScriptTag VARCHAR(100)
,@ScriptGroup VARCHAR(50)
,@SortOrder TINYINT
,@UpdateUserName VARCHAR(10)
,@UpdateHostName VARCHAR(20)
,@HostIP VARCHAR(15)
AS
SET NOCOUNT ON
BEGIN
   UPDATE [DTG].[ScriptDefinition]
   SET [ScriptText] = @ScriptText
      ,[ScriptTag] = @ScriptTag
      ,[ScriptGroup] = @ScriptGroup
      ,[SortOrder] = @SortOrder
      ,[UpdateUserName] = @UpdateUserName
      ,[UpdateHostName] = @UpdateHostName
      ,[UpdateSystemDate] = GETDATE()
      ,[HostIP] = @HostIP
 WHERE [ScriptDefinitionId] = @ScriptDefinitionId
END