
/* KUWAIT TURKISH PARTICIPATION BANK INC.
*
*  All rights are reserved. Reproduction or transmission in whole or in part, in
*  any form or by any means, electronic, mechanical or otherwise, is prohibited
*  without the prior written consent of the copyright owner.
*
*
*  Generator Information
*		Generator				: BOAContainer
*		Generated By			: karadayi
*		Generated Date			: 29/06/2016
*		File Version			: 1.0
*		Purpose					: <Lütfen açıklama giriniz.>
*		Last Modified By		: karadayi
*		Last Modification Date	: 20/10/2016
*
*/
CREATE PROCEDURE [DTG].[upd_TableColumnInformationSecurity]
(
	@TableColumnId INT,
	@Sensitivity TINYINT,
	@DataMaskTypeId TINYINT
)
AS
	SET NOCOUNT ON
	BEGIN

		UPDATE [DTG].[TableColumn]
		   SET Sensitivity = @Sensitivity
		WHERE TableColumnId = @TableColumnId

		IF EXISTS (SELECT 1 FROM DTG.TableColumnDataMask WITH (NOLOCK) WHERE TableColumnId = @TableColumnId)
		BEGIN
			UPDATE DTG.TableColumnDataMask
			   SET DataMaskTypeId = @DataMaskTypeId
			 WHERE TableColumnId = @TableColumnId
		END
		ELSE
		BEGIN
			DECLARE
				@DBName VARCHAR(20),
				@SchemaName VARCHAR(20),
				@TableName VARCHAR(50),
				@ColumnName VARCHAR(100)

			SELECT @DBName = TBL.DBName, @SchemaName = TBL.SchemaName, @TableName = TBL.TableName, @ColumnName = TC.ColumnName 
			  FROM [DTG].[TableColumn] TC WITH (NOLOCK)
			INNER JOIN [DTG].[Table] TBL WITH (NOLOCK) ON
				TBL.TableId = TC.TableId
			 WHERE TC.TableColumnId = @TableColumnId

			INSERT INTO DTG.TableColumnDataMask(TableColumnId, DBName, SchemaName, TableName, ColumnName, DataMaskTypeId)
			VALUES(@TableColumnId, @DBName, @SchemaName, @TableName, @ColumnName, @DataMaskTypeId)
		END

	END