
/* KUWAIT TURKISH PARTICIPATION BANK INC.
*
*  All rights are reserved. Reproduction or transmission in whole or in part, in
*  any form or by any means, electronic, mechanical or otherwise, is prohibited
*  without the prior written consent of the copyright owner.
*
*
*  Generator Information
*		Generator				: BOAContainer
*		Generated By			: karadayi
*		Generated Date			: 05/01/2018
*		File Version			: 1.0
*		Purpose					: <Lütfen açıklama giriniz.>
*		Last Modified By		: karadayi
*		Last Modification Date	: 05/01/2018
*
*/
CREATE PROCEDURE [DTG].[upd_TableColumnSubsetCriteria]
(
	@DBName VARCHAR(50),
	@SchemaName VARCHAR(20),
	@TableName VARCHAR(50),
	@ColumnName VARCHAR(100),
	@SubsetCriteria VARCHAR(50) = NULL,
	@SubsetOperator VARCHAR(20) = NULL
)
AS
	SET NOCOUNT ON
	BEGIN

		IF EXISTS (
			SELECT TOP 1 1 
			  FROM DTG.TableColumnDataMask WITH (NOLOCK)
			 WHERE DBName = @DBName
				AND SchemaName = @SchemaName
				AND TableName = @TableName
				AND ColumnName = @ColumnName
			)
		BEGIN
			UPDATE DTG.TableColumnDataMask
			   SET SubsetCriteria = @SubsetCriteria
				  ,SubsetOperator = @SubsetOperator
			 WHERE DBName = @DBName
				AND SchemaName = @SchemaName
				AND TableName = @TableName
				AND ColumnName = @ColumnName
		END
		ELSE
		BEGIN
			INSERT INTO DTG.TableColumnDataMask(TableColumnId, DBName, SchemaName, TableName, ColumnName, DataMaskTypeId, SubsetCriteria, SubsetOperator)
			VALUES(-1, @DBName, @SchemaName, @TableName, @ColumnName, NULL, @SubsetCriteria, @SubsetOperator)
		END

	END