/* 
*  All rights are reserved. Reproduction or transmission in whole or in part, in
*  any form or by any means, electronic, mechanical or otherwise, is prohibited
*  without the prior written consent of the copyright owner.
*
*
*  Generator Information
*		Generator				: BOAContainer
*		Generated By			: tp.keremcan
*		Generated Date			: 
*		File Version			: 1.0
*		Purpose					: <Lütfen açıklama giriniz.>
*		Last Modified By		: tp.keremc
*		Last Modification Date	: 01/09/2020
*
*/
CREATE PROCEDURE [DTG].[upd_TermValidateByBusinessUnit]
(
	@TermId INT,
	@Name VARCHAR(200),
	@ValidatedByBusinessUnit TINYINT = NULL,
	@NameEN VARCHAR(200) = NULL,
	@DataOwnerId INT = NULL,
	@DataManagerId INT = NULL,
	@AccessibilityId INT = NULL,
	@SensitivityId INT = NULL,
	@IntegrityId INT = NULL,
	@IsPrivateData INT = NULL,
	@Description VARCHAR(2000),
	@DescriptionEN VARCHAR(2000) = NULL,
	@UpdateUserName VARCHAR(10) = NULL,
	@UpdateHostName VARCHAR(20) = NULL,
	@HostIP VARCHAR(15) = NULL
)
AS
SET NOCOUNT ON
BEGIN

	UPDATE [DTG].[Term] 
	   SET
		[ValidatedByBusinessUnit] = @ValidatedByBusinessUnit,
		[Name] = @Name,
		[NameEN] = @NameEN,
		[DataOwner] = @DataOwnerId,
		[DataManager] = @DataManagerId,
		[Sensitivity] = @SensitivityId,
		[Accessibility] = @AccessibilityId,
		[Integrity] = @IntegrityId,
		[IsPrivateData] = @IsPrivateData,
		[Description] = @Description,
		[DescriptionEN] = @DescriptionEN,
		[UpdateUserName] = @UpdateUserName,
		[UpdateHostName] = @UpdateHostName,
		[UpdateSystemDate] = GETDATE(),
		[HostIP] = @HostIP
	WHERE [TermId] = @TermId

END