
/* KUWAIT TURKISH PARTICIPATION BANK INC.
*
*  All rights are reserved. Reproduction or transmission in whole or in part, in
*  any form or by any means, electronic, mechanical or otherwise, is prohibited
*  without the prior written consent of the copyright owner.
*
*
*  Generator Information
*		Generator				: BOAContainer
*		Generated By			: karadayi
*		Generated Date			: 09/06/2016 15:20:01
*		File Version			: 1.0
*		Purpose					: <Lütfen açıklama giriniz.>
*		Last Modified By		: karadayi
*		Last Modification Date	: 09/06/2016 15:20:01
*
*/
CREATE PROCEDURE [DTG].[upd_ColumnRule]
(
	@ColumnRuleId INT,
	@TermId INT,
	@DataType VARCHAR(50),
	@ColumnName VARCHAR(100)
)
AS
BEGIN

	UPDATE [DTG].[ColumnRule] SET
		TermId = @TermId,
		DataType = @DataType,
		ColumnName = @ColumnName
	WHERE ColumnRuleId = @ColumnRuleId

END