
/* KUWAIT TURKISH PARTICIPATION BANK INC.
*
*  All rights are reserved. Reproduction or transmission in whole or in part, in
*  any form or by any means, electronic, mechanical or otherwise, is prohibited
*  without the prior written consent of the copyright owner.
*
*
*  Generator Information
*		Generator				: BOAContainer
*		Generated By			: karadayi
*		Generated Date			: 10/07/2018
*		File Version			: 1.0
*		Purpose					: <Lütfen açıklama giriniz.>
*		Last Modified By		: 
*		Last Modification Date	: 
*
*/
CREATE PROCEDURE [DTG].[upd_ScriptInventory]
@ScriptInventoryId INT
,@ScriptInventoryType TINYINT
,@ScriptDefinitionId INT
,@TermId INT = NULL
,@DatabaseName VARCHAR(100)
,@SchemaName VARCHAR(100)
,@TableName VARCHAR(100)
,@ColumnName VARCHAR(50)
,@UpdateUserName VARCHAR(10)
,@UpdateHostName VARCHAR(20)
,@HostIP VARCHAR(15)
AS
SET NOCOUNT ON
BEGIN
   UPDATE [DTG].[ScriptInventory]
   SET [ScriptInventoryType] = @ScriptInventoryType
      ,[ScriptDefinitionId] = @ScriptDefinitionId
	  ,[TermId] = @TermId
      ,[DatabaseName] = @DatabaseName
      ,[SchemaName] = @SchemaName
      ,[TableName] = @TableName
      ,[ColumnName] = @ColumnName
      ,[UpdateUserName] = @UpdateUserName
      ,[UpdateHostName] = @UpdateHostName
      ,[UpdateSystemDate] = GETDATE()
      ,[HostIP] = @HostIP
 WHERE [ScriptInventoryId] = @ScriptInventoryId
END