
/* KUWAIT TURKISH PARTICIPATION BANK INC.
*
*  All rights are reserved. Reproduction or transmission in whole or in part, in
*  any form or by any means, electronic, mechanical or otherwise, is prohibited
*  without the prior written consent of the copyright owner.
*
*
*  Generator Information
*		Generator				: BOAContainer
*		Generated By			: karadayi
*		Generated Date			: 23/11/2016
*		File Version			: 1.0
*		Purpose					: <Lütfen açıklama giriniz.>
*		Last Modified By		: karadayi
*		Last Modification Date	: 26/01/2017
*
*/
CREATE PROCEDURE [DTG].[upd_TableColumnSecurity]
(
	@DBName VARCHAR(50),
	@SchemaName VARCHAR(20),
	@TableName VARCHAR(50),
	@ColumnName VARCHAR(100),
	@Sensitivity TINYINT,
	@DataMaskTypeId TINYINT
)
AS
	SET NOCOUNT ON
	BEGIN

		UPDATE [DTG].[TableColumn]
		   SET Sensitivity = @Sensitivity
		  FROM [DTG].[TableColumn] TC WITH (NOLOCK)
		 INNER JOIN [DTG].[Table] TBL WITH (NOLOCK) ON
			TBL.TableId = TC.TableId
		 WHERE TBL.DBName = @DBName
			AND TBL.SchemaName = @SchemaName
			AND TBL.TableName = @TableName
			AND TC.ColumnName = @ColumnName

		UPDATE [DTG].[TableColumnDraft]
		   SET Sensitivity = @Sensitivity
		  FROM [DTG].[TableColumnDraft] TC WITH (NOLOCK)
		 INNER JOIN [DTG].[TableDraft] TBL WITH (NOLOCK) ON
			TBL.TableDraftId = TC.TableDraftId
		 WHERE TBL.DBName = @DBName
			AND TBL.SchemaName = @SchemaName
			AND TBL.TableName = @TableName
			AND TC.ColumnName = @ColumnName

		IF EXISTS (
			SELECT TOP 1 1 
			  FROM DTG.TableColumnDataMask WITH (NOLOCK)
			 WHERE DBName = @DBName
				AND SchemaName = @SchemaName
				AND TableName = @TableName
				AND ColumnName = @ColumnName
			)
		BEGIN
			UPDATE DTG.TableColumnDataMask
			   SET DataMaskTypeId = @DataMaskTypeId
			 WHERE DBName = @DBName
				AND SchemaName = @SchemaName
				AND TableName = @TableName
				AND ColumnName = @ColumnName
		END
		ELSE
		BEGIN
			INSERT INTO DTG.TableColumnDataMask(TableColumnId, DBName, SchemaName, TableName, ColumnName, DataMaskTypeId)
			VALUES(-1, @DBName, @SchemaName, @TableName, @ColumnName, @DataMaskTypeId)
		END

	END